/*******************************************************************************
 * Nano_D++ knob fonts: Montserrat Medium, LVGL 9.0 lv_font_fmt_txt, 4 bpp.
 * Source: Montserrat.ttf (variable; wght 500 = named instance "Medium")
 *         sha256 0f7b311b2f3279e4..., units_per_em 1000
 * Renderer: Pillow 12.3.0 / FreeType 2.14.3, BASIC layout, anchor "ls", Pillow's own load flags
 * Generated by harness/gen_lvgl_font.py -- DO NOT EDIT; re-run the generator.
 *
 * cc_font_12: 232 glyphs, U+00A0-017F, U+2013-2014, U+2018-2019, U+201C-201D, U+2022, U+2026 (+ U+0020-007E via lv_font_montserrat_12)
 * cc_font_14: 232 glyphs, U+00A0-017F, U+2013-2014, U+2018-2019, U+201C-201D, U+2022, U+2026 (+ U+0020-007E via lv_font_montserrat_14)
 * cc_font_16: 232 glyphs, U+00A0-017F, U+2013-2014, U+2018-2019, U+201C-201D, U+2022, U+2026 (+ U+0020-007E via lv_font_montserrat_16)
 * cc_font_22: 232 glyphs, U+00A0-017F, U+2013-2014, U+2018-2019, U+201C-201D, U+2022, U+2026 (+ U+0020-007E via lv_font_montserrat_22)
 * cc_font_48: 12 glyphs, U+0025, U+002D, U+0030-0039
 * cc_font_48t: 11 glyphs, U+0030-003A (tabular digits: zero.tf..nine.tf)
 *
 * Hybrid text fonts (cc_font_12, cc_font_14, cc_font_16, cc_font_22): ASCII is NOT
 * stored here; it resolves through the required .fallback lv_font_montserrat_<N>
 * (the cc4 glyphs and kerning), so LV_FONT_MONTSERRAT_<N> must stay 1 for them.
 * Other glyphs outside a font fall back to lv_font_montserrat_<N> only when that
 * built-in is enabled in lv_conf.h. Each font keeps its built-in's line_height
 * and base_line, so a label's baseline sits CC_FONT_<N>_ASCENT px below its top.
 ******************************************************************************/

#ifndef CC_FONTS_H
#define CC_FONTS_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

LV_FONT_DECLARE(cc_font_12)
LV_FONT_DECLARE(cc_font_14)
LV_FONT_DECLARE(cc_font_16)
LV_FONT_DECLARE(cc_font_22)
LV_FONT_DECLARE(cc_font_48)
LV_FONT_DECLARE(cc_font_48t)

/* line_height, base_line (from the bottom) and ascent = line_height - base_line */
#define CC_FONT_12_LINE_HEIGHT 15
#define CC_FONT_12_BASE_LINE 3
#define CC_FONT_12_ASCENT 12
#define CC_FONT_14_LINE_HEIGHT 16
#define CC_FONT_14_BASE_LINE 3
#define CC_FONT_14_ASCENT 13
#define CC_FONT_16_LINE_HEIGHT 18
#define CC_FONT_16_BASE_LINE 3
#define CC_FONT_16_ASCENT 15
#define CC_FONT_22_LINE_HEIGHT 24
#define CC_FONT_22_BASE_LINE 4
#define CC_FONT_22_ASCENT 20
#define CC_FONT_48_LINE_HEIGHT 52
#define CC_FONT_48_BASE_LINE 9
#define CC_FONT_48_ASCENT 43
#define CC_FONT_48T_LINE_HEIGHT 52
#define CC_FONT_48T_BASE_LINE 9
#define CC_FONT_48T_ASCENT 43

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif /*CC_FONTS_H*/
