"""Writes lcd/app_icons_nologo.c: the README's stand-in for the Onshape app icon.

cc_app_icons.c holds Karl Malota's Onshape icons (24x24 and 48x48 RGB565 big-endian) as const arrays
(cc_app_icons.c:7, :82), so the public media cannot patch them at run time: build_lcd.py --no-logo
(CMake README_NO_LOGO) compiles this file in its place. It defines the same two symbols with a generic
badge: a plain hexagon outline in the icon's own two colours (green 0x65E9 and white), nothing shaped
like any vendor's mark. The idle plasma (cc_app_screens.cpp build_field) seeds its distance field from
every non-black pixel, so the hexagon's ring is what the plasma ripples out of.

Usage: python gen_nologo_icons.py   (rewrites lcd/app_icons_nologo.c next to this script)
"""
from __future__ import annotations

import math
from pathlib import Path

GREEN = 0x65E9          # the one green in cc_app_icons.c
WHITE = 0xFFFF
HERE = Path(__file__).resolve().parent


def hexagon(size, thickness, inner_dot):
    """RGB565 big-endian bytes of a size x size hexagon outline (flat top), optional white centre dot."""
    out = bytearray()
    c = (size - 1) / 2.0
    radius = size / 2.0 - 1.5          # circumscribed radius of the outer edge
    for y in range(size):
        for x in range(size):
            dx, dy = x - c, y - c
            # Distance to a flat-top regular hexagon's boundary (sdf): max over the three edge normals.
            d = max(abs(dy), abs(dy * 0.5 + dx * math.sqrt(3) / 2), abs(dy * 0.5 - dx * math.sqrt(3) / 2))
            apothem = radius * math.sqrt(3) / 2
            on_ring = apothem - thickness <= d <= apothem
            dot = inner_dot and math.hypot(dx, dy) <= inner_dot
            color = GREEN if on_ring else WHITE if dot else 0
            out += bytes((color >> 8, color & 0xFF))
    return bytes(out)


def c_array(name, data, size):
    lines = [f"const uint8_t {name}[{size} * {size} * 2] = {{"]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    body = [
        "// README stand-in for cc_app_icons.c (generated by tools/readme-media/gen_nologo_icons.py; do not edit).",
        "// Same symbols, same format (RGB565 big-endian, black = transparent): a plain hexagon outline in the",
        "// icon's two colours instead of the Onshape mark, so public media built with README_NO_LOGO shows no logo.",
        '#include "cc_app_profile.h"',
        "",
        c_array("cc_app_icon_onshape_24", hexagon(24, 2.2, 2.2), 24),
        "",
        c_array("cc_app_icon_onshape_48", hexagon(48, 4.0, 4.5), 48),
        "",
    ]
    (HERE / "lcd" / "app_icons_nologo.c").write_text("\n".join(body), encoding="ascii")
    print("wrote lcd/app_icons_nologo.c")


if __name__ == "__main__":
    main()
