"""Build and run the actual LVGL software renderer. Python stdlib + MSVC only.

Steps (each fails fast):
1. cpp11_gate.py: the shared firmware units must compile in the device's gnu++11.
2. lv_conf.h: the firmware's include/lv_conf.h, copied verbatim except for the
   host overrides listed in HOST_OVERRIDES (so LV_MEM_SIZE, fonts, draw and
   widget settings are the knob's).
3. CMake configure/build with Visual Studio 2022 Build Tools.
4. Run the renderer (bounded by a timeout) and convert its PPMs to PNG
   (recursively; the PPMs are removed once their PNG is written).

Usage: build.py [output-dir] [fixture-dir] [cc5_frames.json] [artwork2-dir]
Then: cc54_report.py [output-dir] checks the renders (regression-checks-cc54.json; cc5.4 + v5
renderer, PRESENTATION_V5.md section 15.3). cc5_report.py is the cc5.3 (presentation 4 geometry)
report and no longer applies to the v5 renderer.

cc5.4: the harness also renders tests/fixtures/frames_v5.json and cc54_copy.json (paths compiled
in), and a third run, lcd-preview-full (CC_DISPLAY_FULL_LAYERS=1: every animated layer 240 x 240),
writes output-dir/full-layers for cc54_report.py's v5_bounded pixel-identity check.

The renderer runs twice: the full harness into output-dir, then with a single
art buffer (--one-buffer: the knob when the second PSRAM buffer is missing, new
covers decoded in place) into output-dir/one-buffer (artwork2 cases, timelines
and handback only). CMake is configured with the firmware src/ and tjpgd_shim/
pinned (-DNANOD_FIRMWARE_SRC, -DNANOD_TJPGD_SHIM), so an override left in the
build cache cannot produce evidence from an overlay; render-index.json records
both paths and cc5_report.py checks them.

artwork2 (1.0.0-cc5.3): the harness also renders 240 px JPEG covers and 32x32 app
icons from harness/artwork2 (make_art_fixtures.py --artwork2), decoded by
the firmware's src/cc_jpeg.cpp through tjpgd_shim/ (see CMakeLists.txt).
"""
from pathlib import Path
import os
import re
import subprocess
import sys
from ppm_to_png import convert

root = Path(__file__).resolve().parent
firmware = root.parent / 'firmware'
cmake = Path('C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe')
RENDER_TIMEOUT_S = 900  # LVGL's assert handler is abort(); any other hang must still fail the build.

# Every host override of the firmware lv_conf.h, with the reason. Nothing else
# differs from the firmware file.
HOST_OVERRIDES = [
    # (macro, firmware value, host value, reason)
    ('LV_USE_TFT_ESPI', '1', '0',
     'ESP-only display driver (TFT_eSPI/SPI); the host flushes into a framebuffer instead'),
]

# 1. C++11 gate (fail fast).
subprocess.run([sys.executable, str(root / 'cpp11_gate.py')], check=True)

# 2. Firmware lv_conf.h, verbatim bytes apart from the override lines.
source = (firmware / 'include' / 'lv_conf.h').read_bytes()
config = source
for macro, device_value, host_value, _ in HOST_OVERRIDES:
    pattern = re.compile(rb'^([ \t]*#define[ \t]+' + macro.encode() + rb'[ \t]+)' + re.escape(device_value.encode()) + rb'\b', re.M)
    config, count = pattern.subn(lambda m: m.group(1) + host_value.encode(), config)
    if count != 1:
        raise SystemExit(f'lv_conf.h: expected exactly one "#define {macro} {device_value}" in the firmware file, found {count}')
banner = ['/* Generated by harness/build.py from firmware/include/lv_conf.h.',
          ' * Verbatim copy except these host-only overrides:']
banner += [f' *   {macro} {device_value} -> {host_value}: {reason}' for macro, device_value, host_value, reason in HOST_OVERRIDES]
banner += [' * Do not edit; edit the firmware file instead. */', '']
config = '\r\n'.join(banner).encode('ascii') + config
# The pool is a floor, not a pinned literal: a larger firmware pool must not break the harness.
mem = re.search(rb'#define[ \t]+LV_MEM_SIZE[ \t]+\((\d+) \* 1024U\)', config)
if not mem or int(mem.group(1)) < 80:
    raise SystemExit('lv_conf.h: LV_MEM_SIZE must be >= 80 KB')
for required in (rb'#define LV_COLOR_DEPTH 16',):
    if required not in config:
        raise SystemExit(f'lv_conf.h: firmware value {required.decode()} not found')
config_path = root / 'lv_conf.h'
if not config_path.exists() or config_path.read_bytes() != config:
    config_path.write_bytes(config)

# Normalize key casing: this environment can contain both Path and PATH, which
# MSBuild rejects even though Windows treats environment names case-insensitively.
env = {key.upper(): value for key, value in os.environ.items()}
out = Path(sys.argv[1]) if len(sys.argv) > 1 else root / 'rendered'
exe = root / 'build/Release/lcd-preview.exe'
inputs = [Path(arg) for arg in sys.argv[2:5]]
run_args = [exe, out] + inputs
one_buffer_args = [exe, '--one-buffer', out / 'one-buffer'] + inputs
full_args = [root / 'build/Release/lcd-preview-full.exe', out / 'full-layers'] + inputs
artwork2 = Path(sys.argv[4]) if len(sys.argv) > 4 else root / 'artwork2'
if not (artwork2 / 'manifest.json').is_file():
    raise SystemExit(f'{artwork2 / "manifest.json"} missing: run make_art_fixtures.py --artwork2')
# Evidence is always built from the real sources: pin every cache path (a scratch NANOD_LV_CONF_DIR left in
# build/CMakeCache.txt by hand or by perf.py would otherwise keep compiling another lv_conf.h).
pins = [f'-DNANOD_FIRMWARE_SRC={(firmware / "src").as_posix()}', f'-DNANOD_TJPGD_SHIM={(root / "tjpgd_shim").as_posix()}',
        f'-DNANOD_LV_CONF_DIR={root.as_posix()}']
for args in (
    [cmake, '-S', root, '-B', root / 'build', '-G', 'Visual Studio 17 2022', '-A', 'x64'] + pins,
    [cmake, '--build', root / 'build', '--config', 'Release', '--parallel', '6', '--target', 'lcd-preview',
     'lcd-preview-full'],
):
    subprocess.run([str(arg) for arg in args], env=env, check=True)
# Stale renders from an earlier run must not survive into this one's report.
for stale in [p for p in out.rglob('*') if p.suffix in ('.ppm', '.png') and p.parent != out]:
    stale.unlink()
subprocess.run([str(arg) for arg in run_args], env=env, check=True, timeout=RENDER_TIMEOUT_S)
subprocess.run([str(arg) for arg in one_buffer_args], env=env, check=True, timeout=RENDER_TIMEOUT_S)
subprocess.run([str(arg) for arg in full_args], env=env, check=True, timeout=RENDER_TIMEOUT_S)
converted = 0
for path in sorted(out.rglob('*.ppm')):
    convert(path)
    path.unlink()
    converted += 1
print(f'converted {converted} PPM render(s) to PNG under {out}')
