"""Firmware C++11 gate for the shared, platform-neutral translation units.

The firmware is built by Arduino-ESP32 2.0.14 with GCC 8.4 in -std=gnu++11.
The host harness (MSVC) and light_tests (MSVC) cannot compile below C++14, so
code that is only valid in C++14/17 would pass on the PC and then break the
device build. This gate compiles every shared unit with the real ESP32-S3
xtensa g++ in gnu++11 mode, the same way PlatformIO does.

Checks, per unit:
1. ``-fsyntax-only`` with the firmware's C++ flags plus -Wall -Wextra
   -Wpedantic. Any error fails. Any diagnostic that names a C++14/17 feature
   ("only available with -std=c++14", "C++14 feature", ...) also fails, because
   GCC 8 reports several of those as warnings in gnu++11.
2. An -O0 object compile, then ``nm`` for undefined *data* symbols of the form
   ``Class::member``. In C++11 an odr-used ``static constexpr`` data member
   needs an out-of-class definition; without it the device link fails (or
   only works by accident of -Os). Rule: keep constant tables at namespace
   scope ``constexpr``.
3. A self-test proves the compiler really rejects a C++14 construct, so the
   gate can never pass vacuously.
4. C units: every generated knob font ``src/fonts/cc_font_*.c`` is compiled
   by the xtensa gcc in the firmware's C mode (-std=gnu99 plus the
   framework's C flags) with -Wall -Wextra -Wpedantic against the firmware
   lv_conf.h. Any output at all (error, warning or note) fails the unit.
5. Firmware source rules (1.0.0-cc5.2): no ``FastLED.addLeds<...>`` (a FastLED
   clockless controller brings back FastLED's own ESP32 RMT driver, whose
   unbounded wait hung the HMI task in 1.0.0-cc5.1), no other RMT user and no
   FastLED ESP32 driver option anywhere in ``src/`` (comments are ignored). A
   self-test proves the rules catch code and skip comments.

No USB, no device access, no PlatformIO. Exit status is non-zero on failure.

Extend SHARED_UNITS when a new platform-neutral .cpp is added (UNIT_INCLUDES
names the host shims a unit needs in place of ESP-IDF headers), and
HEADER_UNITS when a new header-only shared unit is added: its generated
translation unit must odr-use everything the header defines, so that the -O0
object and the nm check see it. C_UNIT_GLOBS picks up C units by pattern.
"""
from pathlib import Path
import re
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parent
WORK = ROOT.parent
FIRMWARE = WORK / 'firmware'
LIBDEPS = FIRMWARE / '.pio' / 'libdeps' / 'nanofoc_d'
TOOLCHAIN = WORK / 'platformio-core' / 'packages' / 'toolchain-xtensa-esp32s3' / 'bin'
GXX = TOOLCHAIN / 'xtensa-esp32s3-elf-g++.exe'
GCC = TOOLCHAIN / 'xtensa-esp32s3-elf-gcc.exe'
NM = TOOLCHAIN / 'xtensa-esp32s3-elf-nm.exe'

# Shared translation units, relative to the firmware src/ directory. These are
# compiled unchanged into the firmware and into a host tool (harness or
# light_tests). Add new platform-neutral units here.
SHARED_UNITS = [
    'cc_lights.cpp',
    'cc_display.cpp',
    'cc_icons.cpp',
    'cc_frame_parse.cpp',  # contract-v4 frame parser (parse_tests.py, MSVC)
    'cc_led_wire.cpp',     # 1.0.0-cc5.2 WS2811 RMT item encoder (led_wire_tests.py, MSVC)
    'cc_jpeg.cpp',         # 1.0.0-cc5.3 ROM TJpgDec glue (jpeg_tests.py, media_tests.py, harness; MSVC)
    'cc_alive.cpp',        # 1.0.0-cc5.4 "Warm · alive" LED engine (alive_tests.py, MSVC)
]

# Extra include directories per shared unit, as system includes: host shims that stand in for
# ESP-IDF headers, exactly as the host tools compile the unit. cc_jpeg.cpp includes only
# <esp_rom_tjpgd.h> and <esp_timer.h>; tjpgd_shim/ maps them onto LVGL's bundled TJpgDec (the
# real ROM header is checked by jpeg_tests.py with the firmware's own compile line).
UNIT_INCLUDES = {
    'cc_jpeg.cpp': [ROOT / 'tjpgd_shim', LIBDEPS / 'lvgl' / 'src' / 'libs' / 'tjpgd'],
}

# Header-only shared units -> the translation unit that odr-uses them (written to the gate's
# temporary directory and checked like SHARED_UNITS). cc_media_store.h (1.0.0-cc5.3) is the
# artwork2 media store plus the COM thread's line transport (media_tests.py, MSVC), which runs
# the same translation unit in its own gnu++11 step.
HEADER_UNITS = {
    'cc_media_store.h': '''// Generated by cpp11_gate.py: the gnu++11 gate for the header-only store.
#include "cc_media_store.h"

namespace {
bool accept_all(const uint8_t*, uint32_t) { return true; }
}

uint32_t cc_media_store_gate() {
    static CCMediaStore store;
    static CCMediaSlot slots[4];
    static uint8_t memory[4 * 16], scratch[8];
    CCMediaConfig config = cc_media_device_config();
    config.kinds[CC_MEDIA_COVER].entries = config.kinds[CC_MEDIA_ICON].entries = 3;
    config.kinds[CC_MEDIA_COVER].slotBytes = config.kinds[CC_MEDIA_ICON].slotBytes = 16;
    store.init(config, memory, slots, nullptr, nullptr, scratch, accept_all);
    JsonDocument request, reply;
    deserializeJson(request, "{\\"id\\":1,\\"op\\":\\"have\\",\\"kind\\":\\"cover\\",\\"keys\\":[\\"a\\"]}");
    store.handle(request.as<JsonVariantConst>(), 1, reply["mediaAck"].to<JsonObject>());
    store.setFrameKey(CC_MEDIA_COVER, "a");
    const uint8_t* data = nullptr;
    uint32_t bytes = 0;
    store.adopt(CC_MEDIA_COVER, "a", &data, &bytes);
    store.releaseDisplay(CC_MEDIA_COVER);
    store.cancelUpload();
    char key[CC_MEDIA_KEY_CHARS + 1];
    cc_media_parse_ack("{\\"media\\":", 9, reply["mediaAck"].to<JsonObject>(), key);
    cc_media_capability_fields(reply["artwork2"].to<JsonObject>(), true, CC_MEDIA_RX_BYTES);
    uint8_t out[3];
    static char text[9];                                  // the COM transport (com_thread.cpp)
    static CCLineAssembler line(text, 8);
    const CCLineEvent event = line.feed('x', 0);
    line.expire(2000, 2000);
    const uint32_t transport = static_cast<uint32_t>(event) + static_cast<uint32_t>(line.length()) +
                               cc_com_idle_ticks(line.partial(), false, false, true, 5) +
                               (cc_bad_line_reply("{\\"art\\"", 6) == CC_BAD_LINE_ART ? 1 : 0) +
                               (cc_art_is_line(line.text(), line.length()) ? 1 : 0);
    return store.version() + store.commits() + store.errors() + store.evictions() + (store.receiving() ? 1 : 0) +
           cc_media_crc32(out, cc_media_base64_decode("QUJD", 4, out, sizeof(out))) + (cc_media_is_line("x", 1) ? 1 : 0) +
           transport;
}
''',
    # Inactivity dim / sleep (2026-09-28): the pure timer, the FOC knob watcher and the button
    # swallow bookkeeping (sleep_tests.py, MSVC). The glue declarations are not odr-used here.
    'cc_sleep.h': '''// Generated by cpp11_gate.py: the gnu++11 gate for the header-only sleep logic.
#include "cc_sleep.h"

uint32_t cc_sleep_gate(uint32_t now, float angle) {
    CCSleepMachine machine;
    CCSleepMachine custom(20000, 60000);
    machine.begin(now);
    const bool swallow = machine.input(now + 1) || custom.input(now);
    const uint32_t states = machine.tick(now + kCCSleepDimMs) + custom.tick(now + kCCSleepOffMs) + machine.state();
    CCSleepFoc foc;
    const CCSleepFocStep step = foc.step(now, angle, true);
    CCSleepButtons buttons;
    const bool dropped = buttons.filter(1, CC_SLEEP_KEY_PRESS, true) && buttons.filter(1, CC_SLEEP_KEY_OTHER, false);
    const char* name = cc_sleep_state_name(CC_SLEEP_DIM);
    return states + machine.idleMs(now + 5) + (swallow ? 1u : 0u) + (step.input ? 1u : 0u) + step.action +
           (foc.motorOff() ? 1u : 0u) + (dropped ? 1u : 0u) + buttons.swallowed() + static_cast<uint32_t>(name[0]) +
           cc_sleep_duty(CC_SLEEP_DIM, 3200) + kCCSleepDisableQuietMs + kCCSleepSettleMs + kCCSleepSettleMaxMs +
           kCCSleepIdleCap + static_cast<uint32_t>(kCCSleepWakeRad * 1000.0f);
}
''',
}

# Firmware source rules checked over src/ (1.0.0-cc5.2, CONTROL_CENTER.md "LED transport"):
# (pattern, why). The RMT peripheral belongs to the bounded transport in cc_led_rmt.cpp; a
# FastLED clockless controller (FastLED.addLeds<CHIPSET, PIN, ...>) would bring back FastLED's
# own RMT driver and interrupt, whose unbounded wait hung the HMI task in 1.0.0-cc5.1.
FIRMWARE_SOURCE_RULES = [
    (re.compile(r'addLeds\s*<'), 'FastLED.addLeds<...> instantiates a FastLED clockless (RMT) controller; '
                                 'register a CCLedController with FastLED.addLeds(&controller, ...) instead'),
    (re.compile(r'\b(?:neopixelWrite|rmtInit|rmtWrite|Adafruit_NeoPixel)\b'),
     'another RMT user next to the LED transport (cc_led_rmt.cpp owns the RMT peripheral)'),
    (re.compile(r'\bFASTLED_RMT_BUILTIN_DRIVER\b|\bFASTLED_ESP32_I2S\b'),
     'a FastLED ESP32 driver option; the LED transport is cc_led_rmt.cpp'),
]
FIRMWARE_SOURCE_GLOBS = ['*.cpp', '*.h', '*.c']

INCLUDES = [FIRMWARE / 'src', FIRMWARE / 'include']
# Third-party headers are system includes so their own warnings do not drown
# out ours; they are still parsed in gnu++11.
SYSTEM_INCLUDES = [LIBDEPS / 'lvgl', LIBDEPS / 'ArduinoJson' / 'src']
# lv_conf.h is found through the firmware include/ directory (PlatformIO uses
# LV_CONF_PATH to point at the same file).
DEFINES = ['LV_CONF_INCLUDE_SIMPLE', 'LV_LVGL_H_INCLUDE_SIMPLE']
# CXXFLAGS/CCFLAGS from framework-arduinoespressif32 tools/platformio-build-esp32s3.py
# that affect language acceptance, plus diagnostics.
FIRMWARE_FLAGS = ['-std=gnu++11', '-fexceptions', '-fno-rtti', '-mlongcalls',
                  '-Wno-unused-parameter', '-Wno-sign-compare', '-Wwrite-strings']
DIAGNOSTIC_FLAGS = ['-Wall', '-Wextra', '-Wpedantic']
# C units (generated fonts), relative to src/, compiled with the framework's C flags.
C_UNIT_GLOBS = ['fonts/cc_font_*.c']
C_FIRMWARE_FLAGS = ['-std=gnu99', '-Os', '-mlongcalls', '-ffunction-sections', '-fdata-sections',
                    '-fno-jump-tables', '-fstrict-volatile-bitfields', '-Wno-old-style-declaration']

NEWER_STANDARD = re.compile(
    r'only available with -std=(?:c|gnu)\+\+(?:1y|14|1z|17|2a|20)'
    r'|-std=(?:c|gnu)\+\+(?:1y|14|1z|17|2a|20)'
    r'|C\+\+(?:1y|14|1z|17|2a|20)\b')
# Undefined data symbols that are allowed (none today).
ODR_ALLOW: set = set()


def base_command(extra_system_includes=()):
    command = [str(GXX)] + FIRMWARE_FLAGS + DIAGNOSTIC_FLAGS
    command += [f'-D{define}' for define in DEFINES]
    command += [f'-I{path}' for path in INCLUDES]
    for path in list(SYSTEM_INCLUDES) + list(extra_system_includes):
        command += ['-isystem', str(path)]
    return command


def run(command):
    result = subprocess.run(command, capture_output=True, text=True, encoding='utf-8', errors='replace')
    return result.returncode, (result.stdout + result.stderr).strip()


def self_test(scratch: Path) -> bool:
    # Relaxed constexpr (C++14) must be rejected in gnu++11.
    probe = scratch / 'cxx14_probe.cpp'
    probe.write_text('constexpr int twice(int x) { int y = x; y *= 2; return y; }\n'
                     'static_assert(twice(2) == 4, "");\n', encoding='utf-8')
    code, output = run([str(GXX), '-std=gnu++11', '-fsyntax-only', str(probe)])
    rejected = code != 0 or bool(NEWER_STANDARD.search(output))
    print(f'self-test: C++14 relaxed constexpr {"rejected" if rejected else "ACCEPTED (gate broken)"}')
    return rejected


def check_unit(unit: str, scratch: Path, label: str = '') -> bool:
    source = FIRMWARE / 'src' / unit
    label = label or unit
    if not source.is_file():
        print(f'FAIL {label}: missing {source}')
        return False
    extra = UNIT_INCLUDES.get(unit, ())
    for path in extra:
        if not Path(path).is_dir():
            print(f'FAIL {label}: host shim directory missing: {path}')
            return False
    ok = True
    code, output = run(base_command(extra) + ['-fsyntax-only', str(source)])
    newer = [line for line in output.splitlines() if NEWER_STANDARD.search(line)]
    if output:
        print(output)
    if code != 0:
        print(f'FAIL {label}: gnu++11 syntax errors (exit {code})')
        ok = False
    if newer:
        print(f'FAIL {label}: {len(newer)} diagnostic(s) name a C++14/17 feature')
        ok = False
    if not ok:
        return False
    obj = scratch / (Path(unit).stem + '.o')
    code, output = run(base_command(extra) + ['-O0', '-c', str(source), '-o', str(obj)])
    if code != 0:
        print(output)
        print(f'FAIL {label}: -O0 object compile failed (exit {code})')
        return False
    code, output = run([str(NM), '-C', '--undefined-only', str(obj)])
    if code != 0:
        print(output)
        print(f'FAIL {label}: nm failed (exit {code})')
        return False
    suspects = []
    for line in output.splitlines():
        name = line.split(None, 1)[-1].strip() if line.strip() else ''
        if ('::' in name and '(' not in name and not name.startswith(('std::', 'vtable for', 'typeinfo', '__cxxabi'))
                and name not in ODR_ALLOW):
            suspects.append(name)
    if suspects:
        print(f'FAIL {label}: undefined class data members (odr-used static constexpr?): {", ".join(sorted(set(suspects)))}')
        return False
    print(f'PASS {label}')
    return True


def check_header_unit(header: str, scratch: Path) -> bool:
    """HEADER_UNITS[header], written to `scratch`, checked like a shared unit."""
    if not (FIRMWARE / 'src' / header).is_file():
        print(f'FAIL {header}: missing {FIRMWARE / "src" / header}')
        return False
    tu = scratch / (Path(header).stem + '_gate.cpp')
    tu.write_text(HEADER_UNITS[header], encoding='utf-8', newline='\n')
    return check_unit(str(tu), scratch, label=f'{header} (via {tu.name})')


def strip_comments(text: str) -> str:
    """C/C++ source without // and /* */ comments (string and character literals kept)."""
    out, i, n = [], 0, len(text)
    while i < n:
        c = text[i]
        if c in '"\'':
            j = i + 1
            while j < n and text[j] != c and text[j] != '\n':
                j += 2 if text[j] == '\\' else 1
            out.append(text[i:j + 1])
            i = j + 1
        elif text.startswith('//', i):
            j = text.find('\n', i)
            i = n if j < 0 else j
        elif text.startswith('/*', i):
            j = text.find('*/', i + 2)
            out.append('\n' * text.count('\n', i, n if j < 0 else j))   # keep line numbers
            i = n if j < 0 else j + 2
        else:
            out.append(c)
            i += 1
    return ''.join(out)


def check_firmware_sources() -> bool:
    """FIRMWARE_SOURCE_RULES over every firmware source file (comments ignored)."""
    ok, checked = True, 0
    for pattern in FIRMWARE_SOURCE_GLOBS:
        for path in sorted((FIRMWARE / 'src').rglob(pattern)):
            checked += 1
            code = strip_comments(path.read_text(encoding='utf-8', errors='replace'))
            for rule, why in FIRMWARE_SOURCE_RULES:
                for match in rule.finditer(code):
                    line = code.count('\n', 0, match.start()) + 1
                    print(f'FAIL {path.relative_to(FIRMWARE).as_posix()}:{line}: {match.group(0)!r}: {why}')
                    ok = False
    print(f'{"PASS" if ok else "FAIL"} firmware source rules ({len(FIRMWARE_SOURCE_RULES)} rules over {checked} files '
          'in src/): no FastLED clockless controller, no other RMT user')
    return ok


def firmware_rules_self_test() -> bool:
    """The rules must catch a real use and ignore the same text in comments."""
    code = strip_comments('// FastLED.addLeds<WS2811, 38, RGB>(leds, 60);\n/* rmtInit(1) */\n'
                          'const char* s = "// not a comment";\nFastLED.addLeds<WS2811, 38, RGB>(leds, 60);\n')
    hits = [m.group(0) for rule, _ in FIRMWARE_SOURCE_RULES for m in rule.finditer(code)]
    ok = hits == ['addLeds<'] and '"// not a comment"' in code
    print(f'self-test: firmware source rules {"catch code and skip comments" if ok else "BROKEN"}')
    return ok


def c_command() -> list:
    command = [str(GCC)] + C_FIRMWARE_FLAGS + DIAGNOSTIC_FLAGS + [f'-D{define}' for define in DEFINES]
    command += [f'-I{path}' for path in INCLUDES]
    for path in SYSTEM_INCLUDES:
        command += ['-isystem', str(path)]
    return command


def c_self_test(scratch: Path) -> bool:
    # A warning-only C unit must be caught by the "any output fails" rule.
    probe = scratch / 'c_probe.c'
    probe.write_text('#include "lvgl.h"\nint cc_probe(void) { int unused; return 0; }\n', encoding='utf-8')
    code, output = run(c_command() + ['-fsyntax-only', str(probe)])
    caught = code == 0 and 'unused' in output
    print(f'self-test: C warning {"reported" if caught else "NOT reported (gate broken)"}')
    return caught


def c_units() -> list:
    return sorted(str(path.relative_to(FIRMWARE / 'src')).replace('\\', '/')
                  for pattern in C_UNIT_GLOBS for path in (FIRMWARE / 'src').glob(pattern))


def check_c_unit(unit: str) -> bool:
    source = FIRMWARE / 'src' / unit
    code, output = run(c_command() + ['-fsyntax-only', str(source)])
    if output:
        print(output)
    if code != 0 or output:
        print(f'FAIL {unit}: gnu99 compile {"failed (exit " + str(code) + ")" if code else "produced output"}')
        return False
    print(f'PASS {unit} (C, gnu99, silent)')
    return True


def main() -> int:
    for tool in (GXX, GCC, NM):
        if not tool.is_file():
            print(f'FAIL: toolchain not found: {tool}')
            return 2
    if not (LIBDEPS / 'lvgl' / 'lvgl.h').is_file() or not (LIBDEPS / 'ArduinoJson' / 'src').is_dir():
        print(f'FAIL: PlatformIO library dependencies missing under {LIBDEPS}')
        return 2
    print(f'C++11 gate: {GXX.name} ({" ".join(FIRMWARE_FLAGS[:1])}) over {len(SHARED_UNITS)} shared unit(s) '
          f'and {len(HEADER_UNITS)} header-only unit(s)')
    with tempfile.TemporaryDirectory(prefix='cpp11-gate-') as temp:
        scratch = Path(temp)
        if not self_test(scratch):
            return 1
        results = [check_unit(unit, scratch) for unit in SHARED_UNITS]
        results += [check_header_unit(header, scratch) for header in HEADER_UNITS]
        passed = sum(results)
        print(f'C++11 gate: {passed}/{len(results)} unit(s) passed')
        units = c_units()
        if not units:
            print(f'FAIL: no C units match {C_UNIT_GLOBS} under {FIRMWARE / "src"}')
            return 1
        print(f'C unit gate: {GCC.name} ({C_FIRMWARE_FLAGS[0]}) over {len(units)} unit(s)')
        if not c_self_test(scratch):
            return 1
    c_results = [check_c_unit(unit) for unit in units]
    print(f'C unit gate: {sum(c_results)}/{len(c_results)} unit(s) passed')
    rules = firmware_rules_self_test() and check_firmware_sources()
    return 0 if all(results) and all(c_results) and rules else 1


if __name__ == '__main__':
    sys.exit(main())
