// r4 M9 Play <-> Pause morph strip (design_handoff_nano_d_r4 README 3.2 / 3.5; motion-lab.js morphPP(), variant
// A "Melt"): 12 A8 frames of the 20 px footer glyph between the knob's own `pause` (M8 5v14M16 5v14) and `play`
// (M7 4.5v15l12-7.5z) of export_handoff_icons.cjs, drawn with the same renderer, stroke (2.3 of 24 units, round caps
// and joins) and size. At m = k / 13 (k = 1..12): the left bar's ends move to the triangle's left edge, the right
// bar's ends converge on the apex, and the two sloped edges (bar top -> bar top, bar bottom -> bar bottom) come in
// with opacity m. The end states are the shipped glyphs themselves (the firmware shows `pause` / `play` there).
//
//   node export_morph_strip.cjs            write src/cc_icon_morph.cpp / .h
//   node export_morph_strip.cjs --check    exit 1 when the files differ from a fresh export (the build gate)
'use strict';
const fs = require('fs'); const path = require('path');
function loadSharp() {
  const bundled = process.env.SHARP_MODULE_PATH || 'sharp';
  try { return require(bundled); } catch (e) { return require('sharp'); }
}
const sharp = loadSharp();
const root = path.resolve(__dirname, '../..');
const FIRMWARE_SRC = path.join(root, 'firmware/src');
const SIZE = 20, STROKE = '2.3', FRAMES = 12;
const CHECK = process.argv.slice(2).includes('--check');

const lerp = (a, b, m) => a + (b - a) * m;
const P = (x, y) => `${x.toFixed(3)} ${y.toFixed(3)}`;

function frameSvg(m) {
  // pause bars A (8,5)-(8,19), B (16,5)-(16,19); play triangle (7,4.5) (7,19.5) (19,12).
  const aTop = [lerp(8, 7, m), lerp(5, 4.5, m)], aBot = [lerp(8, 7, m), lerp(19, 19.5, m)];
  const bTop = [lerp(16, 19, m), lerp(5, 12, m)], bBot = [lerp(16, 19, m), lerp(19, 12, m)];
  const style = `fill="none" stroke="white" stroke-width="${STROKE}" stroke-linecap="round" stroke-linejoin="round"`;
  const bars = `<path d="M${P(...aTop)}L${P(...aBot)}M${P(...bTop)}L${P(...bBot)}" ${style}/>`;
  const edges = `<path d="M${P(...aTop)}L${P(...bTop)}M${P(...bBot)}L${P(...aBot)}" ${style} stroke-opacity="${m.toFixed(4)}"/>`;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${SIZE}" height="${SIZE}" viewBox="0 0 24 24">${bars}${edges}</svg>`;
}

async function alphaOf(svg) {
  const {data, info} = await sharp(Buffer.from(svg)).png().toBuffer().then(png =>
    sharp(png).ensureAlpha().raw().toBuffer({resolveWithObject: true}));
  if (info.width !== SIZE || info.height !== SIZE) throw new Error(`rendered ${info.width}x${info.height}`);
  const alpha = Buffer.alloc(SIZE * SIZE);
  for (let i = 3, j = 0; i < data.length; i += info.channels, j++) alpha[j] = data[i];
  return alpha;
}

async function main() {
  const frames = [];
  for (let k = 1; k <= FRAMES; k++) frames.push(await alphaOf(frameSvg(k / (FRAMES + 1))));
  const header = `#pragma once
#include <lvgl.h>
#include <stdint.h>

// Generated by harness/export_morph_strip.cjs. Do not edit.
// r4 M9 (design_handoff_nano_d_r4 README 3.2 / 3.5): the Play <-> Pause morph of the 20 px footer glyph, ${FRAMES} A8
// frames between \`pause\` (frame 0) and \`play\` (frame ${FRAMES + 1}), the shipped glyphs being the two ends.
constexpr uint8_t CC_ICON_MORPH_FRAMES = ${FRAMES};
// Frame k (1..${FRAMES}) of the morph pause -> play; nullptr outside 1..${FRAMES}.
const lv_image_dsc_t* cc_icon_morph(uint8_t k);
`;
  let cpp = `// Generated by harness/export_morph_strip.cjs. Do not edit.
// ${FRAMES} x ${SIZE} x ${SIZE} A8 = ${FRAMES * SIZE * SIZE} B.
#include "cc_icon_morph.h"
#if LV_BIG_ENDIAN_SYSTEM
#error "cc_icon_morph.cpp header initialisers assume the little-endian lv_image_header_t field order"
#endif
namespace {
`;
  frames.forEach((alpha, i) => {
    cpp += `const uint8_t morph_${i + 1}_data[] = {${Array.from(alpha).join(',')}};\n`;
    cpp += `const lv_image_dsc_t morph_${i + 1} = { {LV_IMAGE_HEADER_MAGIC, LV_COLOR_FORMAT_A8, 0, ${SIZE}, ${SIZE}, ${SIZE}, 0}, ${SIZE * SIZE}, morph_${i + 1}_data };\n`;
  });
  cpp += `const lv_image_dsc_t* const kFrames[${FRAMES}] = {${frames.map((_, i) => `&morph_${i + 1}`).join(', ')}};
}  // namespace

const lv_image_dsc_t* cc_icon_morph(uint8_t k) { return k >= 1 && k <= CC_ICON_MORPH_FRAMES ? kFrames[k - 1] : nullptr; }
`;
  const files = {[path.join(FIRMWARE_SRC, 'cc_icon_morph.h')]: header, [path.join(FIRMWARE_SRC, 'cc_icon_morph.cpp')]: cpp};
  if (CHECK) {
    const stale = Object.entries(files).filter(([f, text]) => !fs.existsSync(f) || fs.readFileSync(f, 'utf8') !== text);
    if (stale.length) { console.log('export_morph_strip: stale ' + stale.map(([f]) => path.basename(f)).join(', ')); process.exit(1); }
    console.log('export_morph_strip: cc_icon_morph.cpp/.h are current');
    return;
  }
  for (const [f, text] of Object.entries(files)) { fs.writeFileSync(f, text); console.log('wrote ' + f); }
}
main().catch(e => { console.error(e); process.exit(1); });
