"""LCD thread decisions (lcd_thread.cpp; lane F3). Python stdlib + MSVC + the firmware's xtensa g++; no device, no USB.

lcd_thread.cpp itself is device-only (Arduino, FreeRTOS, TFT_eSPI), so its decisions live in the header-only
src/cc_lcd_logic.h, which this runner proves three ways:

1. gnu++11: cpp11_gate.HEADER_UNITS['cc_lcd_logic.h'] (a translation unit that odr-uses every function of
   cc_lcd_logic.h; build.py's gate runs it too) goes through cpp11_gate.check_header_unit() (the device's xtensa g++ in -std=gnu++11, -Wall -Wextra -Wpedantic, the nm check).
2. lcd_thread_tests.cpp (MSVC /W4 /WX) runs the pure cases; lcd_thread_lvgl_tests.cpp runs the cases that need a
   real LVGL 9 display (the firmware's pinned LVGL and lv_conf.h, built and cached by sleep_tests.build_lvgl()).
3. Pins the firmware wiring the cases rest on, as source text of lcd_thread.cpp (comments ignored).

Findings: FW-PERF-009 (lcd_manager re-applied unchanged texts every second), FW-PERF-010 (lcdRefrUsAvg / lcdRefrUsMax
windowed per second like lcdFps), FW-BUG-042 (the offline layer's native input is native motion, not the raw FOC
position the offline volume rebases), FW-BUG-043 (a handback never returns to the boot splash), FW-BUG-044 (the
cadence poll is told LVGL is paused while the app canvas is up; the real-LVGL case is main.cpp's cadence app_session),
FW-BUG-045 (the app canvas does not move for the swallowed wake turn: lcd_thread_appcanvas_tests.cpp drives the
firmware's unchanged cc_app_* units the way the LCD thread does), FW-PUB-006 (a "Calibrating - hands off" cue on the
top layer while the FOC task aligns the motor: lcd_thread_lvgl_tests.cpp runs lcd_thread.cpp's own cal_cue_apply(),
copied verbatim into build/lcd-thread-tests/cal_cue_fw.inc, with the firmware font), FW-BUG-030 (the same label reads
"Calibration failed - replug" while the FOC task posts CC_MOTOR_CAL_FAILED, until the retry or a recalibration).

Run it under the harness lock: python work/audit/tools/with_lock.py harness -- python harness/lcd_thread_tests.py
Exit status is non-zero on any failure.
"""
from __future__ import annotations

from pathlib import Path
import re
import subprocess
import sys
import tempfile
import time

root = Path(__file__).resolve().parent
sys.path.insert(0, str(root))
import cpp11_gate  # noqa: E402
import sleep_tests  # noqa: E402  (msvc_env, build_lvgl, code, the LVGL cache)

src = sleep_tests.src
out_dir = root / 'build' / 'lcd-thread-tests'
# The app canvas units (as app_canvas_tests.py builds them), for FW-BUG-045.
APP_UNITS_CPP = ('cc_app_canvas.cpp', 'cc_app_gfx.cpp', 'cc_app_fonts.cpp', 'cc_app_shape.cpp', 'cc_app_cards.cpp',
                 'cc_app_screens.cpp')
APP_UNITS_C = ('cc_app_onshape.c', 'cc_app_icons.c', 'cc_app_store.c')   # + the app profile store (acquire / release)

# The gnu++11 translation unit is cpp11_gate.HEADER_UNITS['cc_lcd_logic.h'], so build.py's gate and this runner
# check the same code (it odr-uses every function of cc_lcd_logic.h).
GATE_HEADER = 'cc_lcd_logic.h'


def gnu11_gate() -> None:
    if GATE_HEADER not in cpp11_gate.HEADER_UNITS:
        raise SystemExit(f'FAIL: cpp11_gate.HEADER_UNITS has no {GATE_HEADER} (build.py would not gate it)')
    with tempfile.TemporaryDirectory() as tmp:
        if not cpp11_gate.check_header_unit(GATE_HEADER, Path(tmp)):
            raise SystemExit('FAIL: cc_lcd_logic.h is not valid gnu++11 for the device')


def compile_pure() -> Path:
    cl, env = sleep_tests.msvc_env()
    exe = out_dir / 'lcd_thread_tests.exe'
    subprocess.run([
        str(cl), '/nologo', '/EHsc', '/std:c++14', '/W4', '/WX', '/O2', '/D_CRT_SECURE_NO_WARNINGS',
        f'/I{src}', str(root / 'lcd_thread_tests.cpp'), f'/Fo{out_dir}\\', f'/Fe{exe}',
    ], cwd=out_dir, env=env, check=True)
    return exe


def cal_cue_source() -> str:
    """FW-PUB-006: lcd_thread.cpp's cue (its state and cal_cue_apply()), verbatim, for lcd_thread_lvgl_tests.cpp."""
    raw = (src / 'lcd_thread.cpp').read_text(encoding='utf-8')
    m = re.search(r'^CCCalCue cal_cue = \{\};\n.*?^void cal_cue_apply\(uint8_t action\) \{\n.*?^\}\n', raw, flags=re.S | re.M)
    if not m:
        raise SystemExit('FAIL: lcd_thread.cpp: the cue state and cal_cue_apply() not found (FW-PUB-006)')
    return '// Generated by lcd_thread_tests.py: copied verbatim from src/lcd_thread.cpp.\n' + m.group(0)


def compile_lvgl() -> Path:
    conf_dir = sleep_tests.build_lvgl()
    cl, env = sleep_tests.msvc_env()
    exe = out_dir / 'lcd_thread_lvgl_tests.exe'
    (out_dir / 'cal_cue_fw.inc').write_text(cal_cue_source(), encoding='utf-8', newline='\n')
    lvgl_inc = ['/DLV_CONF_INCLUDE_SIMPLE', '/DLV_LVGL_H_INCLUDE_SIMPLE', '/external:W0',
                f'/external:I{conf_dir}', f'/external:I{sleep_tests.LVGL}']
    # FW-PUB-006: the cue's font, the firmware's generated C file (its ../ui.h is src/ui.h).
    font_obj = out_dir / 'ui_font_SGK100h16.obj'
    subprocess.run([str(cl), '/nologo', '/TC', '/std:c11', '/W3', '/O2', '/c', *lvgl_inc, f'/I{src}',
                    str(src / 'fonts' / 'ui_font_SGK100h16.c'), f'/Fo{font_obj}'], cwd=out_dir, env=env, check=True)
    subprocess.run([
        str(cl), '/nologo', '/EHsc', '/std:c++14', '/W4', '/WX', '/O2', '/D_CRT_SECURE_NO_WARNINGS',
        *lvgl_inc, f'/I{src}', f'/I{out_dir}', str(root / 'lcd_thread_lvgl_tests.cpp'), str(font_obj),
        f'/Fo{out_dir}\\', f'/Fe{exe}', '/link', str(sleep_tests.lvgl_dir / 'lvgl.lib'),
    ], cwd=out_dir, env=env, check=True)
    return exe


def compile_appcanvas() -> Path:
    cl, env = sleep_tests.msvc_env()
    obj = out_dir / 'appcanvas-obj'
    obj.mkdir(parents=True, exist_ok=True)
    for unit in APP_UNITS_C:      # C99 data, compiled as C (/TC) as the device does
        subprocess.run([str(cl), '/nologo', '/TC', '/std:c11', '/W4', '/WX', '/O2', '/c', f'/I{src}', str(src / unit),
                        f'/Fo{obj}\\'], cwd=out_dir, env=env, check=True)
    exe = out_dir / 'lcd_thread_appcanvas_tests.exe'
    subprocess.run([str(cl), '/nologo', '/EHsc', '/std:c++14', '/W4', '/WX', '/O2', '/D_CRT_SECURE_NO_WARNINGS',
                    f'/I{src}', str(root / 'lcd_thread_appcanvas_tests.cpp'),
                    *(str(src / unit) for unit in APP_UNITS_CPP), *(str(obj / (Path(u).stem + '.obj')) for u in APP_UNITS_C),
                    f'/Fo{obj}\\', f'/Fe{exe}'], cwd=out_dir, env=env, check=True)
    return exe


def pins() -> int:
    count = 0
    lcd = sleep_tests.read('lcd_thread.cpp')

    def need(pattern, what):
        nonlocal count
        if not re.search(pattern, lcd):
            raise SystemExit(f'FAIL: lcd_thread.cpp: {what} (pattern {pattern!r} not found)')
        count += 1

    need(r'#include "cc_lcd_logic\.h"', 'includes cc_lcd_logic.h')
    # FW-PERF-009: every received command moves the count; lcd_manager returns before the value-screen block unless
    # the gate says so, and records the application after it.
    need(r'if \(xQueueReceive\(_q_lcd_in, &cmd, \(TickType_t\)0\)\) \{ last_command = cmd; \+\+lcd_command_seq; \}',
         'handleLcdCommand() counts every received LcdCommand')
    need(r'lcd_thread\.handleLcdCommand\(\); static CCLcdManagerGate manager_gate = \{\}; '
         r'if \(!cc_lcd_manager_due\(manager_gate, lv_scr_act\(\) == ui_valueScreen, lcd_command_seq, '
         r'lcd_text_set\(lcd_thread\.last_command\.data3\)\)\) return; if \(lv_scr_act\(\)==ui_valueScreen\)\{',
         'lcd_manager runs its value-screen block only when the gate says so')
    block = re.search(r'static void lcd_manager\(lv_timer_t \* lcd_cmd_timer\) \{(.*?)\n?static void idle_anim_handler',
                      lcd, flags=re.S)
    if not block or not block.group(1).rstrip().endswith('cc_lcd_manager_applied(manager_gate, lcd_command_seq); }'):
        raise SystemExit('FAIL: lcd_thread.cpp: lcd_manager records the application as its last statement')
    count += 1
    if lcd.count('++lcd_command_seq') != 1 or lcd.count('lv_label_set_text_fmt(ui_profileName') != 1:
        raise SystemExit('FAIL: lcd_thread.cpp: one command count, one profile name write (inside the gated block)')
    count += 1
    # FW-PERF-010: the refresh mean and max come from the window only (no since-boot accumulator left), published
    # in perfWindow() with lcdFps; perfRefrReady() only adds to the window.
    need(r'\+\+winFrames; cc_refr_window_add\(winRefr, us\);', 'perfRefrReady() adds each refresh to the window')
    need(r'uint32_t refrAvg = 0, refrMax = 0; cc_refr_window_close\(winRefr, refrAvg, refrMax\); '
         r'portENTER_CRITICAL\(&perfLock\); perf\.lcdFps = winFrames \* 1000u / span; perf\.lcdRefrUsAvg = refrAvg; '
         r'perf\.lcdRefrUsMax = refrMax;', 'perfWindow() publishes the window mean and max with lcdFps')
    for gone in ('refrUsSum', 'refrCount'):
        if gone in lcd:
            raise SystemExit(f'FAIL: lcd_thread.cpp: the since-boot accumulator {gone} is back')
    if len(re.findall(r'perf\.lcdRefrUs(?:Avg|Max) =', lcd)) != 2:
        raise SystemExit('FAIL: lcd_thread.cpp: lcdRefrUsAvg / lcdRefrUsMax are written only in perfWindow()')
    count += 2
    # FW-BUG-042: the offline layer's position input is the native motion count of the FOC position, the offline
    # volume's flag and its step count; nothing else feeds cc_offline_input_update().
    need(r'const uint32_t keyEdges = cc_native_button_seq\(\); const uint16_t motion = cc_native_motion_step\('
         r'cc_native_motion, foc_thread\.pass_cur_pos\(\), cc_offline_wanted\(\), cc_offline_steps\(\), millis\(\)\); '
         r'cc_display_offline\(cc_offline_input_update\(cc_offline_in, motion, keyEdges\)\);',
         'the offline layer is fed native motion (FW-BUG-042)')
    if lcd.count('cc_offline_input_update(') != 1 or lcd.count('cc_native_motion_step(') != 1:
        raise SystemExit('FAIL: lcd_thread.cpp: one offline input update, fed by the one native motion step')
    if 'cc_offline_input_update' in sleep_tests.read('cc_display.cpp'):
        raise SystemExit('FAIL: cc_display.cpp: the offline input lives in cc_lcd_logic.h only')
    count += 1
    # FW-BUG-043: the handback loads cc_handback_screen() of the previous screen, the splash and the value screen.
    need(r'void hand_back\(\) \{ lv_screen_load\(cc_handback_screen\(cc_previous_screen, ui_bootimg, ui_valueScreen\)\);',
         'hand_back() never loads the boot splash (FW-BUG-043)')
    if lcd.count('lv_screen_load(') != 2:
        raise SystemExit('FAIL: lcd_thread.cpp: two screen loads (entering the host screen, the handback)')
    count += 1
    # FW-BUG-044: the cadence poll knows LVGL is paused while the app canvas is up (app_on), so an app session
    # ends the episode instead of counting as one late, session-long interval (main.cpp cadence app_session).
    need(r'void perfCadence\(bool lvglPaused\) \{ if \(!cc_anim_cadence_poll\(cc_cadence, lvglPaused\)\) return;',
         'perfCadence() passes the pause to the cadence poll (FW-BUG-044)')
    need(r'if \(!app_on\) lv_timer_handler\(\); lcd_backlight_apply\(\); perfCadence\(app_on\);',
         'the loop samples the cadence with app_on, the flag that skipped lv_timer_handler() (FW-BUG-044)')
    if lcd.count('perfCadence(') != 2 or not re.search(
            r'cc_anim_cadence_sample\(cadence, timer->last_run, !lvglPaused && lv_anim_count_running\(\) > 0, '
            r'timer->period\);', sleep_tests.read('cc_display.cpp')):
        raise SystemExit('FAIL: cc_display.cpp: a paused pass is sampled as the end of the episode (FW-BUG-044)')
    count += 1
    # FW-BUG-045: the hold is stepped first thing on every pass (asleep too) with the raw angle and the sleep state,
    # and the canvas only ever gets the held angle.
    need(r'void render_host_frame\(\) \{ app_angle_held = app_angle_hold\.step\(cc_app_angle_read\(\), '
         r'cc_sleep_state\(\) == CC_SLEEP_ASLEEP, millis\(\)\);', 'the app angle hold runs on every pass (FW-BUG-045)')
    need(r'CCAppInputs app_inputs\(\) \{ CCAppInputs in; in\.nowMs = millis\(\); in\.angle = app_angle_held;',
         'the app canvas gets the held angle (FW-BUG-045)')
    if lcd.count('cc_app_angle_read()') != 1:
        raise SystemExit('FAIL: lcd_thread.cpp: the raw app angle is read only by the hold')
    count += 1
    # FW-PUB-006: every pass steps the "hands off" cue with the FOC task's calibration word, before LVGL runs, and
    # the cue is one label on the top layer (over any screen) with the cc_lcd_logic.h text; nothing else posts it.
    need(r'#include "cc_boot_cal\.h"', 'includes cc_boot_cal.h (FW-PUB-006)')
    # FW-BUG-030: the same step gets the failed state of the same word, and the label shows the failed text for it.
    # The step gets the whole word: a failed boot alignment reads "replug" only once its one retry is done.
    need(r'lcd_sleep_gate\.refreshed\(\); \} cal_cue_apply\(cc_cal_cue_step\(cal_cue, cc_motor_cal_state\(\)\)\); '
         r'cc_crumb_lcd\(CC_LCD_STEP_TIMERS\); if \(!app_on\) lv_timer_handler\(\);',
         'every pass steps the cue with the calibration word before lv_timer_handler() (FW-PUB-006, FW-BUG-030)')
    need(r'cal_cue_label = lv_label_create\(lv_layer_top\(\)\);',
         'the cue is a top-layer label (FW-PUB-006)')
    need(r'lv_label_set_text\(cal_cue_label, action == CC_CAL_CUE_SHOW_FAILED \? kCCCalFailedCueText : kCCCalCueText\);',
         'the cue shows kCCCalFailedCueText for a failed alignment, kCCCalCueText otherwise (FW-BUG-030)')
    if lcd.count('cal_cue_apply(') != 2 or lcd.count('cc_cal_cue_step(') != 1 or lcd.count('lv_layer_top()') != 1:
        raise SystemExit('FAIL: lcd_thread.cpp: one cue step, one cal_cue_apply() call, one top-layer object (FW-PUB-006)')
    count += 1
    # FW-BUG-017: right after lv_init() a mixed lv_conf.h image (main.cpp's cc_lvgl_layout_ok() false) parks in
    # cc_lvgl_layout_halt(): it draws a fixed error with TFT_eSPI alone, touches no lv_* call and never returns, so no
    # display, host screen or lv_obj is created; the check is the only statement between lv_init() and the tick.
    need(r'#include "nanofoc_d\.h"', 'includes nanofoc_d.h for cc_lvgl_layout_ok() (FW-BUG-017)')
    need(r'lv_init\(\); if \(!cc_lvgl_layout_ok\(\)\) cc_lvgl_layout_halt\(\); lv_tick_set_cb\(cc_tick_ms\);',
         'run() checks the LVGL layout right after lv_init() (FW-BUG-017)')
    halt = re.search(r'static void cc_lvgl_layout_halt\(\) \{(.*?) while \(1\) \{ cc_wdt_feed\(\); '
                     r'vTaskDelay\(1000 / portTICK_PERIOD_MS\); \} \}', lcd)
    if not halt:
        raise SystemExit('FAIL: lcd_thread.cpp: cc_lvgl_layout_halt() never returns and feeds the watchdog (FW-BUG-017)')
    body = halt.group(1)
    if re.search(r'\blv_|\bui_|lcd_backlight\(', body) or not re.search(
            r'^ tft\.begin\(\); tft\.setRotation\(3\); tft\.fillScreen\(TFT_RED\);.*'
            r'ledcWrite\(LEDC_CH_LCD_BKL, LEDC_MAX_BLK\);$', body):
        raise SystemExit(f'FAIL: lcd_thread.cpp: the halt draws with TFT_eSPI only, backlight on (FW-BUG-017): {body!r}')
    run = lcd[lcd.index('void LcdThread::run() {'):]
    if lcd.count('cc_lvgl_layout_ok()') != 1 or not (
            run.index('cc_lvgl_layout_halt();') < run.index('lv_display_create(') < run.index('ui_init();')):
        raise SystemExit('FAIL: lcd_thread.cpp: one layout check, before the display and the host screen (FW-BUG-017)')
    count += 1
    return count


def firmware_syntax() -> None:
    """FW-BUG-017: lcd_thread.cpp (now including nanofoc_d.h) still compiles with its exact firmware compile line
    (xtensa g++ -fsyntax-only via boot_pins_tests; no build, no PlatformIO). Skipped when the database is absent."""
    import boot_pins_tests
    if not (boot_pins_tests.firmware / 'compile_commands.json').exists():
        print('SKIP lcd_thread.cpp xtensa syntax: no compile_commands.json')
        return
    boot_pins_tests.WARNING_BUDGET.setdefault('lcd_thread.cpp', 0)
    if not boot_pins_tests.firmware_syntax(['lcd_thread.cpp']):
        raise SystemExit('FAIL: lcd_thread.cpp: xtensa g++ -fsyntax-only')


def main() -> int:
    started = time.time()
    pinned = pins()
    firmware_syntax()
    gnu11_gate()
    out_dir.mkdir(parents=True, exist_ok=True)
    subprocess.run([str(compile_pure())], check=True)
    subprocess.run([str(compile_lvgl())], check=True)
    subprocess.run([str(compile_appcanvas())], check=True)
    print(f'PASS: LCD thread logic (cc_lcd_logic.h) and {pinned} firmware wiring pin(s) [{time.time() - started:.1f} s]')
    return 0


if __name__ == '__main__':
    sys.exit(main())
