"""Write firmware/src/cc_crumbs.{h,cpp}: the r3 arc breadcrumbs as A8 masks (README r3 section 2.1).

The masks come from app/control_center/crumb_arc.py (the one source the desktop mirror
paints too): per `crumb` token, the ancestors mask (#7C7C7C, may be absent) and the current level's mask
(#E6E6E6), each cropped to its ink with its top-left on the LCD. The firmware draws them as LVGL A8 images
recoloured to the ink, straight from flash (no RAM copy).

Usage: .venv\\Scripts\\python.exe harness\\make_crumbs.py [--check]
--check: exit 1 when the files on disk differ from what would be written (the build gate).
"""
from __future__ import annotations

import sys
from pathlib import Path

root = Path(__file__).resolve().parent
companion = root.parent / 'app'
sys.path.insert(0, str(companion))
from control_center import crumb_arc, presentation  # noqa: E402

SRC = root.parent / 'firmware' / 'src'
ENUM = ('CC_CRUMB_MUSIC', 'CC_CRUMB_RECENT', 'CC_CRUMB_ONSCREEN_RECENT', 'CC_CRUMB_ONSCREEN_PLAYLISTS',
        'CC_CRUMB_TRACKS', 'CC_CRUMB_UPNEXT', 'CC_CRUMB_WINDOWS', 'CC_CRUMB_LIGHTS', 'CC_CRUMB_SCENES',
        'CC_CRUMB_PLAYLISTS')
LAST = ENUM[-1]

HEADER = '''#pragma once
#include <stdint.h>
#include "cc_presentation.h"

// Generated by harness/make_crumbs.py from control_center/crumb_arc.py. Do not edit.
// The r3 arc breadcrumbs (README r3 section 2.1; PRESENTATION_V5.md section 19.9): per CCCrumb, the ancestors
// mask (#7C7C7C, w == 0 when the path has one level) and the current level's mask (#E6E6E6). A8, row-major,
// top-left (x, y) on the 240 x 240 LCD. Montserrat 500 12 px caps, 0.96 px tracking, on r 94 about (120,120).

struct CCCrumbMask {
    int16_t x, y;
    uint16_t w, h;
    const uint8_t* data;   // w * h alpha bytes (nullptr when w == 0)
};

constexpr uint32_t CC_CRUMB_ANCESTOR_INK = 0x%06X;
constexpr uint32_t CC_CRUMB_CURRENT_INK = 0x%06X;
constexpr uint32_t CC_CRUMB_FADE_MS = 200;      // README r3 section 4: arc and pips 200 ms

// The mask of `crumb` (1..10): current = true for the current level, false for the ancestors; nullptr for
// CC_CRUMB_NONE or an unknown value, or when that part is empty.
const CCCrumbMask* cc_crumb_mask(uint8_t crumb, bool current);
// Screen depth of a crumb's screen (README r3 section 4: music / windows / lights 1, albums / tracks /
// scenes / playlists 2, explorer / upnext 3); 0 for none (the launcher Home).
uint8_t cc_crumb_depth(uint8_t crumb);
'''


def c_bytes(data):
    lines = []
    for i in range(0, len(data), 24):
        lines.append('    ' + ', '.join(f'0x{b:02X}' for b in data[i:i + 24]) + ',')
    return '\n'.join(lines)


def source():
    # Append-only: the host's presentation.CRUMBS is crumb_arc's order (a host that does not send a newer token
    # yet, e.g. `playlists` before its controller change lands, is a prefix of it).
    host = tuple(presentation.CRUMBS)
    assert tuple(crumb_arc.TOKENS[:len(host)]) == host, 'crumb_arc.PATHS order must extend presentation.CRUMBS'
    assert len(crumb_arc.TOKENS) == len(ENUM), 'one CCCrumb per crumb_arc token'
    parts = ['// Generated by harness/make_crumbs.py from control_center/crumb_arc.py. Do not edit.',
             '#include "cc_crumbs.h"', '', 'namespace {']
    table = []
    total = 0
    for k, token in enumerate(crumb_arc.TOKENS):
        masks = crumb_arc.render(token)
        entry = []
        for part, mask in zip(('anc', 'cur'), masks):
            name = f'k{token[0].upper()}{token[1:]}_{part}'
            if mask is None:
                entry.append('{0, 0, 0, 0, nullptr}')
                continue
            total += len(mask.data)
            parts.append(f'// {token} {part}: {mask.w} x {mask.h} at ({mask.x}, {mask.y})')
            parts.append(f'const uint8_t {name}[{len(mask.data)}] = {{')
            parts.append(c_bytes(mask.data))
            parts.append('};')
            entry.append(f'{{{mask.x}, {mask.y}, {mask.w}, {mask.h}, {name}}}')
        table.append((ENUM[k], entry, crumb_arc.DEPTH[token]))
    parts.append('')
    parts.append('// [CCCrumb - 1][0 ancestors, 1 current]')
    parts.append(f'const CCCrumbMask kMasks[{len(ENUM)}][2] = {{')
    for enum, entry, _depth in table:
        parts.append(f'    {{{entry[0]}, {entry[1]}}},   // {enum}')
    parts.append('};')
    parts.append(f'const uint8_t kDepth[{len(ENUM)}] = {{' + ', '.join(str(d) for _e, _en, d in table) + '};')
    parts.append('}  // namespace')
    parts.append('')
    parts.append('''const CCCrumbMask* cc_crumb_mask(uint8_t crumb, bool current) {
    if (crumb == CC_CRUMB_NONE || crumb > LAST) return nullptr;
    const CCCrumbMask& mask = kMasks[crumb - 1][current ? 1 : 0];
    return mask.w ? &mask : nullptr;
}

uint8_t cc_crumb_depth(uint8_t crumb) {
    return crumb == CC_CRUMB_NONE || crumb > LAST ? 0 : kDepth[crumb - 1];
}'''.replace('LAST', LAST))
    parts.append(f'// {total} mask bytes in flash.')
    return '\n'.join(parts) + '\n'


def main():
    header = HEADER % (crumb_arc.ANCESTOR_INK, crumb_arc.CURRENT_INK)
    files = {SRC / 'cc_crumbs.h': header, SRC / 'cc_crumbs.cpp': source()}
    if '--check' in sys.argv[1:]:
        stale = [p.name for p, text in files.items() if not p.is_file() or p.read_text(encoding='utf-8') != text]
        if stale:
            print('make_crumbs: stale ' + ', '.join(stale))
            return 1
        print('make_crumbs: cc_crumbs.h/.cpp are current')
        return 0
    for path, text in files.items():
        path.write_text(text, encoding='utf-8', newline='\n')
        print(f'wrote {path}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
