"""r4 motion tokens (design_handoff_nano_d_r4 README section 3.1; the r3.1 prototype's cssSpring()): the four
springs baked into 41-point step-response tables over their settle time, as the prototype's CSS linear() curves.

    SPRING.snap 0.36 s / 0.72, soft 0.46 / 0.82, pop 0.42 / 0.52, wall 0.34 / 0.42 (response, damping), mass 1:
    k = (2 pi / response)^2, c = 4 pi damping / response; settle = the first ms (from 40, step 8) after which the
    response stays within 0.4 % of 1 for 120 ms (step 8); the table is f(settle * i / 40), i = 0..40, the last 1.

The firmware (src/cc_display.cpp, kSpringLut) stores them as int16 (x 4096) with the settle ms; the Desk Dial
Navigator (stage/curves.py) and control_center/motion.py evaluate the same analytic curves.

Usage: make_motion.py            print the C++ table
       make_motion.py --check    exit 1 when src/cc_display.cpp's table differs (the harness gate)
"""
from __future__ import annotations

import math
import re
import sys
from pathlib import Path

SPRINGS = (('snap', 0.36, 0.72), ('soft', 0.46, 0.82), ('pop', 0.42, 0.52), ('wall', 0.34, 0.42))
POINTS = 41
SCALE = 4096
SRC = Path(__file__).resolve().parent.parent / 'firmware' / 'src' / 'cc_display.cpp'


def constants(response, damping):
    k = (2 * math.pi / response) ** 2
    c = 4 * math.pi * damping / response
    return k, c


def step_response(response, damping):
    k, c = constants(response, damping)
    w0 = math.sqrt(k)
    z = c / (2 * w0)

    def f(ms):
        t = ms / 1000.0
        if z < 1:
            wd = w0 * math.sqrt(1 - z * z)
            return 1 - math.exp(-z * w0 * t) * (math.cos(wd * t) + (z * w0 / wd) * math.sin(wd * t))
        return 1 - math.exp(-w0 * t) * (1 + w0 * t)
    return f


def settle_ms(f):
    for ms in range(40, 1600, 8):
        if all(abs(1 - f(ms + j)) <= 0.004 for j in range(0, 121, 8)):
            return ms
    return 1200


def table(response, damping):
    f = step_response(response, damping)
    st = settle_ms(f)
    pts = [f(st * i / (POINTS - 1)) for i in range(POINTS)]
    pts[-1] = 1.0
    return st, [int(round(p * SCALE)) for p in pts]


def cpp():
    lines = ['// Generated by harness/make_motion.py (r4 README 3.1 springs, the r3.1 prototype\'s cssSpring()):',
             '// {settle ms, 41 samples of the step response x 4096 over the settle time}. Order: snap, soft, pop, wall.',
             'constexpr SpringLut kSpringLut[4] = {']
    for name, r, z in SPRINGS:
        st, pts = table(r, z)
        k, c = constants(r, z)
        lines.append(f'    // {name}: response {r} s, damping {z}; k {k:.1f}, c {c:.1f}; overshoot {max(pts) / SCALE - 1:.1%}')
        lines.append(f'    {{{st}, {{' + ', '.join(str(p) for p in pts) + '}},')
    lines.append('};')
    return '\n'.join(lines)


def main(argv):
    text = cpp()
    if '--check' in argv:
        src = SRC.read_text(encoding='utf-8')
        m = re.search(r'// Generated by harness/make_motion\.py.*?\n};', src, re.S)
        if not m or m.group(0) != text:
            print('make_motion: src/cc_display.cpp kSpringLut is stale (run make_motion.py and paste)')
            return 1
        print('make_motion: kSpringLut is current')
        return 0
    print(text)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
