"""FW-BUG-022 init_pd() NVM skip pins (lane F8: hmi_thread.cpp). Python stdlib + MSVC (+ xtensa for --firmware-syntax).

HmiThread::init_pd() may skip the STUSB4500 NVM write only when the live sink table is the one it programs:
PDO count 2, PDO1 5 V, PDO2 and PDO3 9 V. Whenever it does write, it calls cc_boot_pd_nvm_rewritten() before
cc_boot_pd(...), so the FOC task assumes the high supply until the next power cycle. The sink PDOs and RDO_STATUS
are read BEFORE the rewrite (SparkFun setVoltage() writes the volatile DPM registers), so the stored contract
voltage is the one the running contract was negotiated against.

1. Source rules over hmi_thread.cpp (comments stripped).
2. A behaviour test: init_pd()'s body and stusb_sink_table_ours() are cut verbatim from hmi_thread.cpp and
   compiled (MSVC /W4 /WX) against a fake STUSB4500, a fake register read and recording cc_boot_pd* calls.
--firmware-syntax: also syntax-checks hmi_thread.cpp (boot_pins_tests.firmware_syntax: xtensa g++ -fsyntax-only, no build).
Writes build/pd-nvm-tests/*. Exit status is non-zero on any failure.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

root = Path(__file__).resolve().parent
sys.path.insert(0, str(root))
import media_tests  # noqa: E402

src = media_tests.firmware / 'src'
out_dir = root / 'build' / 'pd-nvm-tests'


def code(text: str) -> str:
    text = re.sub(r'/\*.*?\*/', ' ', text, flags=re.S)
    return re.sub(r'//[^\n]*', ' ', text)


def block(text: str, signature: str) -> str:
    """The signature through its matching closing brace ('' when absent)."""
    match = re.search(signature + r'\s*\{', text)
    if not match:
        return ''
    depth = 0
    for i in range(match.end() - 1, len(text)):
        depth += {'{': 1, '}': -1}.get(text[i], 0)
        if depth == 0:
            return text[match.start():i + 1]
    return ''


def squash(text: str) -> str:
    return re.sub(r'\s+', '', text)


INIT_PD = r'PowerType\s+HmiThread::init_pd\s*\(\s*\)'
OURS = (r'bool\s+stusb_sink_table_ours\s*\(\s*uint8_t\s+pdoCount\s*,\s*uint32_t\s+pdo1\s*,\s*uint32_t\s+pdo2\s*,'
        r'\s*uint32_t\s+pdo3\s*\)')


def rules(hmi: str) -> bool:
    ok = True

    def check(name: str, cond: bool) -> None:
        nonlocal ok
        ok &= bool(cond)
        print(f'{"PASS" if cond else "FAIL"} {name}')

    init_pd = squash(block(hmi, INIT_PD))
    ours = squash(block(hmi, OURS))
    check('init_pd() is found', bool(init_pd))
    check('stusb_sink_table_ours() checks the count and all three voltages',
          'pdoCount==2u' in ours and '((pdo1>>10)&0x3FFu)==kSinkPdo1Units' in ours
          and '((pdo2>>10)&0x3FFu)==kSinkPdo2Units' in ours and '((pdo3>>10)&0x3FFu)==kSinkPdo3Units' in ours)
    check('the table units are 5 V, 9 V and 9 V in 50 mV steps',
          re.search(r'kSinkPdo1Units\s*=\s*5000u\s*/\s*50u\s*;', hmi) is not None
          and re.search(r'kSinkPdo2Units\s*=\s*9000u\s*/\s*50u\s*;', hmi) is not None
          and re.search(r'kSinkPdo3Units\s*=\s*9000u\s*/\s*50u\s*;', hmi) is not None)
    check('init_pd() no longer skips the write on the count alone', 'getPdoNumber()!=2' not in init_pd)
    check('init_pd() gates the write on stusb_sink_table_ours() over the three PDOs',
          'stusb_sink_table_ours(usb_pd.getPdoNumber(),sinkPdo[0],sinkPdo[1],sinkPdo[2])' in init_pd
          and 'constboolnvmRewritten=!sinkTableOurs;' in init_pd and 'if(nvmRewritten){' in init_pd)
    first_set = init_pd.find('usb_pd.set')
    check('every register read (sink PDOs, RDO_STATUS) comes before the first setVoltage()/set*() call',
          first_set > 0 and init_pd.find('stusb_read32(kStusbRdoStatus,rdo)') >= 0
          and init_pd.rfind('stusb_read32(') < first_set)
    write = init_pd.find('usb_pd.write();')
    flag = init_pd.find('if(nvmRewritten)cc_boot_pd_nvm_rewritten();')
    report = init_pd.find('cc_boot_pd(rdoOk,rdo,millivolts);')
    check('init_pd() writes once and flags every rewrite',
          init_pd.count('usb_pd.write();') == 1 and init_pd.count('cc_boot_pd_nvm_rewritten();') == 1)
    check('cc_boot_pd_nvm_rewritten() runs before cc_boot_pd(rdoOk, rdo, millivolts), both after the write',
          0 <= write < flag < report)
    return ok


HARNESS = r'''// Generated by pd_nvm_pins_tests.py (FW-BUG-022): init_pd() cut verbatim from hmi_thread.cpp, against fakes.
#include <cstdint>
#include <cstdio>
#include <map>
#include <string>
#include <vector>
#define PIN_NANO_I2C_SDA 1
#define PIN_NANO_I2C_SCL 2
enum PowerType { POWER_5V_USB };
struct FakeWire { void begin(int, int) {} } Wire;
struct FakeSerial { void println(const char*) {} } Serial;
static std::vector<std::string> calls;
static std::map<uint8_t, uint32_t> regs;
static std::map<uint8_t, bool> failing;
static bool volatileTouched = false;    // a set*() call changed the chip's volatile DPM registers
static int readsAfterSet = 0;
constexpr uint8_t kStusbRdoStatus = 0x91;
constexpr uint8_t kStusbSinkPdo1 = 0x85;
struct FakePd {
    bool present = true;
    uint8_t count = 2;
    int writes = 0;
    bool begin() { return present; }
    uint8_t getPdoNumber() { calls.push_back("count"); return count; }
    void setUsbCommCapable(bool) { volatileTouched = true; }
    // As SparkFun's setVoltage(): writes the volatile DPM_SNK_PDOn register directly (bits 19:10, 50 mV).
    void setVoltage(uint8_t n, float v) {
        volatileTouched = true;
        const uint8_t reg = static_cast<uint8_t>(kStusbSinkPdo1 + 4u * (n - 1u));
        regs[reg] = (regs[reg] & ~0xFFC00u) | (static_cast<uint32_t>(v * 20.0f) << 10);
    }
    void setCurrent(uint8_t, float) { volatileTouched = true; }
    void setLowerVoltageLimit(uint8_t, uint8_t) { volatileTouched = true; }
    void setUpperVoltageLimit(uint8_t, uint8_t) { volatileTouched = true; }
    void setPdoNumber(uint8_t value) { volatileTouched = true; count = value; }
    void write() { ++writes; calls.push_back("write"); }
} usb_pd;
bool stusb_read32(uint8_t reg, uint32_t& value) {
    if (volatileTouched) ++readsAfterSet;
    if (failing[reg]) return false;
    value = regs[reg];
    return true;
}
static bool rewrittenFlag = false;
static bool reportedOk = false;
static uint32_t reportedRdo = 0, reportedMv = 0;
static int reports = 0;
void cc_boot_pd_nvm_rewritten() { rewrittenFlag = true; calls.push_back("rewritten"); }
void cc_boot_pd(bool readOk, uint32_t rdo, uint32_t mv) {
    ++reports; reportedOk = readOk; reportedRdo = rdo; reportedMv = mv;
    calls.push_back(rewrittenFlag ? "pd+flag" : "pd");
}
@OURS@
struct HmiThread { PowerType init_pd(); };
@INIT_PD@

static uint32_t pdo(uint32_t millivolts) { return ((millivolts / 50u) << 10) | 300u; }   // + 3 A current bits
static int failures = 0;
struct Case {
    const char* name;
    uint8_t count; uint32_t mv1, mv2, mv3;
    bool fail1, fail2, fail3;
    bool rdoFail; uint32_t position;
    bool expectWrite; uint32_t expectMv;
};
static void run(const Case& c) {
    calls.clear(); regs.clear(); failing.clear(); rewrittenFlag = false; volatileTouched = false; readsAfterSet = 0;
    reports = 0; reportedOk = false; reportedRdo = 0; reportedMv = 0;
    usb_pd.writes = 0; usb_pd.count = c.count;
    regs[kStusbSinkPdo1] = pdo(c.mv1); regs[kStusbSinkPdo1 + 4] = pdo(c.mv2); regs[kStusbSinkPdo1 + 8] = pdo(c.mv3);
    regs[kStusbRdoStatus] = (c.position << 28) | 0x1234u;
    failing[kStusbSinkPdo1] = c.fail1; failing[kStusbSinkPdo1 + 4] = c.fail2; failing[kStusbSinkPdo1 + 8] = c.fail3;
    failing[kStusbRdoStatus] = c.rdoFail;
    HmiThread h;
    h.init_pd();
    bool ok = (usb_pd.writes == (c.expectWrite ? 1 : 0)) && rewrittenFlag == c.expectWrite;
    // The report always comes last, and after a write the flag is already set when cc_boot_pd() runs.
    ok = ok && reports == 1 && !calls.empty() && calls.back() == (c.expectWrite ? "pd+flag" : "pd");
    if (c.expectWrite) {
        size_t w = 0, r = 0;
        for (size_t i = 0; i < calls.size(); ++i) { if (calls[i] == "write") w = i; if (calls[i] == "rewritten") r = i; }
        ok = ok && w < r;
    }
    // Every register read precedes the rewrite, and the store gets the PRE-rewrite contract.
    ok = ok && readsAfterSet == 0;
    ok = ok && reportedOk == !c.rdoFail && reportedRdo == (c.rdoFail ? 0u : regs[kStusbRdoStatus]);
    ok = ok && reportedMv == c.expectMv;
    std::printf("%s %s (mv %u)\n", ok ? "PASS" : "FAIL", c.name, static_cast<unsigned>(reportedMv));
    if (!ok) ++failures;
}

int main() {
    const Case cases[] = {
        {"our table (2 PDOs, 5 / 9 / 9 V) skips the write, 9 V contract", 2, 5000, 9000, 9000, false, false, false, false, 2, false, 9000},
        {"our table, no explicit contract (position 0)", 2, 5000, 9000, 9000, false, false, false, false, 0, false, 0},
        {"our table, failed RDO read: no write, read reported failed", 2, 5000, 9000, 9000, false, false, false, true, 2, false, 0},
        {"2 PDOs at 5 / 12 V is rewritten, contract reported at 12 V", 2, 5000, 12000, 9000, false, false, false, false, 2, true, 12000},
        {"foreign 5 / 20 V table is rewritten, contract reported at 20 V (not the new 9 V)", 2, 5000, 20000, 20000, false, false, false, false, 2, true, 20000},
        {"2 PDOs at 5 / 9 V with PDO3 20 V is rewritten", 2, 5000, 9000, 20000, false, false, false, false, 3, true, 20000},
        {"2 PDOs at 9 / 9 V is rewritten", 2, 9000, 9000, 9000, false, false, false, false, 1, true, 9000},
        {"factory 3 PDOs (5 / 15 / 20 V) is rewritten, contract at 20 V", 3, 5000, 15000, 20000, false, false, false, false, 3, true, 20000},
        {"3 PDOs at 5 / 9 / 9 V is rewritten", 3, 5000, 9000, 9000, false, false, false, false, 2, true, 9000},
        {"1 PDO is rewritten", 1, 5000, 9000, 9000, false, false, false, false, 1, true, 5000},
        {"a failed PDO1 read is rewritten", 2, 5000, 9000, 9000, true, false, false, false, 2, true, 9000},
        {"a failed PDO2 read is rewritten, its voltage unknown", 2, 5000, 9000, 9000, false, true, false, false, 2, true, 0},
        {"a failed PDO3 read is rewritten", 2, 5000, 9000, 9000, false, false, true, false, 2, true, 9000},
        {"a position past the sink table is unknown", 2, 5000, 9000, 9000, false, false, false, false, 4, false, 0},
    };
    for (const Case& c : cases) run(c);
    std::printf("%s: init_pd NVM skip (%d failures)\n", failures ? "FAIL" : "PASS", failures);
    return failures ? 1 : 0;
}
'''


def behaviour(hmi_raw: str) -> bool:
    hmi = code(hmi_raw)
    init_pd, ours = block(hmi, INIT_PD), block(hmi, OURS)
    units = re.findall(r'constexpr\s+uint32_t\s+kSinkPdo[123]Units\s*=[^;]*;', hmi)
    if not init_pd or not ours or len(units) != 3:
        print('FAIL behaviour: init_pd() / stusb_sink_table_ours() / the unit constants not found')
        return False
    out_dir.mkdir(parents=True, exist_ok=True)
    cpp = out_dir / 'pd_nvm_tests.cpp'
    cpp.write_text(HARNESS.replace('@OURS@', '\n'.join(units) + '\n' + ours).replace('@INIT_PD@', init_pd),
                   encoding='utf-8', newline='\n')
    cl, env = media_tests.msvc_env()
    exe = out_dir / 'pd_nvm_tests.exe'
    result = subprocess.run([str(cl), '/nologo', '/EHsc', '/std:c++17', '/W4', '/WX', '/wd4100', str(cpp),
                             f'/Fo{out_dir}\\', f'/Fe{exe}'], cwd=out_dir, env=env, capture_output=True,
                            text=True, encoding='utf-8', errors='replace')
    if result.returncode:
        print((result.stdout + result.stderr)[-4000:])
        print('FAIL behaviour: MSVC /W4 /WX build')
        return False
    return subprocess.run([str(exe)]).returncode == 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    parser.add_argument('--firmware-syntax', action='store_true')
    args = parser.parse_args()
    raw = (src / 'hmi_thread.cpp').read_text(encoding='utf-8', errors='replace')
    ok = rules(code(raw))
    ok &= behaviour(raw)
    if args.firmware_syntax:
        import boot_pins_tests   # its check counts hmi_thread.cpp's older warnings against a budget
        ok &= boot_pins_tests.firmware_syntax(['hmi_thread.cpp'])
    print(f'{"PASS" if ok else "FAIL"}: init_pd NVM skip pins')
    return 0 if ok else 1


if __name__ == '__main__':
    sys.exit(main())
