#pragma once
#include <stdint.h>
#include "cc_presentation.h"

// Generated by harness/make_crumbs.py from control_center/crumb_arc.py. Do not edit.
// The r3 arc breadcrumbs (README r3 section 2.1; PRESENTATION_V5.md section 19.9): per CCCrumb, the ancestors
// mask (#7C7C7C, w == 0 when the path has one level) and the current level's mask (#E6E6E6). A8, row-major,
// top-left (x, y) on the 240 x 240 LCD. Montserrat 500 12 px caps, 0.96 px tracking, on r 94 about (120,120).

struct CCCrumbMask {
    int16_t x, y;
    uint16_t w, h;
    const uint8_t* data;   // w * h alpha bytes (nullptr when w == 0)
};

constexpr uint32_t CC_CRUMB_ANCESTOR_INK = 0x7C7C7C;
constexpr uint32_t CC_CRUMB_CURRENT_INK = 0xE6E6E6;
constexpr uint32_t CC_CRUMB_FADE_MS = 200;      // README r3 section 4: arc and pips 200 ms

// The mask of `crumb` (1..10): current = true for the current level, false for the ancestors; nullptr for
// CC_CRUMB_NONE or an unknown value, or when that part is empty.
const CCCrumbMask* cc_crumb_mask(uint8_t crumb, bool current);
// Screen depth of a crumb's screen (README r3 section 4: music / windows / lights 1, albums / tracks /
// scenes / playlists 2, explorer / upnext 3); 0 for none (the launcher Home).
uint8_t cc_crumb_depth(uint8_t crumb);
