#pragma once
#include <lvgl.h>
// Design icon masks (A8), generated by harness/export_handoff_icons.cjs.
// Sizes by use (PRESENTATION_V5.md section 9.1): 20 px every wire token and the internal "heartfill"
// (footer; tone liked draws it in #A3244A instead of "heart", P5-R29); 26 px play, pause, list, win,
// tracks (Home idle row); 16 px prev, next and the internal "dotfill" (Tracks row).
// Returns nullptr for an unknown name or a token without a mask at that size (the caller hides it).
const lv_image_dsc_t* cc_icon(const char* name, int size);
