#pragma once
#include <lvgl.h>
#include <stdint.h>

// Generated by harness/export_morph_strip.cjs. Do not edit.
// r4 M9 (design_handoff_nano_d_r4 README 3.2 / 3.5): the Play <-> Pause morph of the 20 px footer glyph, 12 A8
// frames between `pause` (frame 0) and `play` (frame 13), the shipped glyphs being the two ends.
constexpr uint8_t CC_ICON_MORPH_FRAMES = 12;
// Frame k (1..12) of the morph pause -> play; nullptr outside 1..12.
const lv_image_dsc_t* cc_icon_morph(uint8_t k);
