/* Nano_D++ r2 — single source for the motion table, blur recipes and copy sheet.
   Rendered by Browse and Snap.dc.html and exported to specs/01 §A–C. */
(function () {
  const OUT = 'cubic-bezier(0.22,1,0.36,1)', IN = 'cubic-bezier(0.4,0,1,1)', SPR = 'cubic-bezier(0.34,1.45,0.64,1)', LIN = 'linear';
  const M = (surf, el, prop, from, to, ms, delay, curve, when) => ({ surf, el, prop, from, to, ms, delay, curve, when });
  const motion = [
    // Music explorer
    M('Explorer', 'Overlay root', 'opacity', '0', '1', 340, 0, OUT, 'Open (reverse on close: 1→0, 340, OUT)'),
    M('Explorer', 'Card (enter)', 'translateY · scale', '+30 · ×0.9', '0 · table', 440, '45 × distance', OUT, 'Open, source switch (only times a stagger is used)'),
    M('Explorer', 'Card (enter)', 'opacity', '0', 'table', 320, '45 × distance', OUT, 'Open, source switch'),
    M('Explorer', 'Card (exit)', 'translateY · scale · opacity', '0 · table · table', '+30 · ×0.9 · 0', 170, 0, IN, 'Source switch; new source enters at 190 ms'),
    M('Explorer', 'Card (turn)', 'translateX · scale', 'table(d)', 'table(d∓1)', 420, 0, OUT, 'Each detent; retarget mid-flight, never queue'),
    M('Explorer', 'Card (turn)', 'opacity', 'table(d)', 'table(d∓1)', 300, 0, OUT, 'Each detent'),
    M('Explorer', 'Card shade (#0B0B0C)', 'opacity', 'table(d)', 'table(d∓1)', 320, 0, OUT, 'Each detent'),
    M('Explorer', 'Card shadow', 'crossfade', 'side shadow', 'focus shadow', 320, 0, OUT, 'Card enters or leaves the centre'),
    M('Explorer', 'Row (end stop)', 'translateX', '0', '∓14 → 0', 160, 0, OUT, 'Turn past either end'),
    M('Explorer', 'Tab underline', 'scaleX', '0', '1', 320, 0, OUT, 'Button 2 / 3; fixed 2 px bar, square ends'),
    M('Explorer', 'Tab label', 'opacity', '0.55', '1', 240, 0, OUT, 'Button 2 / 3'),
    M('Explorer', 'Position marker', 'translateX', 'i × 14', '(i±1) × 14', 420, 0, OUT, 'Each detent; fixed 6 × 6 square over fixed dots'),
    M('Explorer', 'Label (title/sub/meta)', 'opacity', '0', '1', 160, 0, OUT, 'Text swaps when the detent lands, then fades in'),
    M('Explorer', 'Ambient layer', 'crossfade A↔B', 'previous cover', 'focused cover', 600, 200, OUT, '200 ms after the last detent; newest wins in a fast spin'),
    M('Explorer', 'Centre card (play)', 'scale', '1', '1.12', 380, 0, OUT, 'Button 4; other cards opacity → 0, 300 ms; overlay closes at 380'),
    // Up next
    M('Up next', 'Overlay root', 'opacity', '0', '1', 340, 0, OUT, 'Open / close'),
    M('Up next', 'Left column', 'translateY · opacity', '+20 · 0', '0 · 1', 460, 0, OUT, 'Open (opacity 320 ms)'),
    M('Up next', 'Row (enter)', 'translateX · opacity', '+40 · 0', '0 · table', 420, '40 × distance', OUT, 'Open, after shuffle (opacity 300 ms)'),
    M('Up next', 'Row (turn)', 'translateY · scale', 'table(d)', 'table(d∓1)', 420, 0, OUT, 'Each detent'),
    M('Up next', 'Row (turn)', 'opacity', 'table(d)', 'table(d∓1)', 300, 0, OUT, 'Each detent'),
    M('Up next', 'Focus plate', '—', 'static', 'static', 0, 0, '—', 'Fixed at the focus line; rows move through it'),
    M('Up next', 'Big cover', 'crossfade A↔B', 'previous', 'focused track cover', 420, 120, OUT, 'Playlists only, 120 ms after the last detent; newest wins'),
    M('Up next', 'Ambient layer', 'crossfade A↔B', 'previous', 'focused track cover', 600, 200, OUT, 'Same trigger as the explorer'),
    M('Up next', 'Heart', 'scale', '0.4', '1.5 → 1', 380, 0, SPR, 'Like lands (opacity 0→1, 200 ms)'),
    M('Up next', 'Rows (shuffle)', 'opacity', 'table', '0', 160, 0, IN, 'Button 2; reordered rows re-enter with the open stagger'),
    M('Up next', 'Row (end stop)', 'translateY', '0', '∓14 → 0', 160, 0, OUT, 'Turn past either end'),
    // Window picker
    M('Windows', 'Overlay root', 'opacity', '0', '1', 280, 0, OUT, 'Open / close'),
    M('Windows', 'Card (enter)', 'translateY · scale · opacity', '+24 · ×0.92 · 0', '0 · table · table', 420, 0, OUT, 'Open'),
    M('Windows', 'Card (turn)', 'translateX · scale', 'table(d)', 'table(d∓1)', 420, 0, OUT, 'Each detent'),
    M('Windows', 'Card (turn)', 'opacity', 'table(d)', 'table(d∓1)', 300, 0, OUT, 'Each detent'),
    M('Windows', 'Selection frame', 'opacity', '0', '1', 320, 0, OUT, 'Card enters the centre (2 px square frame, separate layer)'),
    M('Windows', 'Card shadow', 'crossfade', 'side shadow', 'focus shadow', 320, 0, OUT, 'Card enters or leaves the centre'),
    M('Windows', 'Snap tray', 'translateY · scale', '−14 · 0.94', '0 · 1', 460, 0, SPR, 'First snap (opacity 260 ms OUT)'),
    M('Windows', 'Carousel group', 'translateY', '−44', '0', 460, 0, OUT, 'First snap'),
    M('Windows', 'Slot fill', 'opacity', '0', '1', 260, 0, OUT, 'Snap lands'),
    M('Windows', 'Snap thumbnail (fly)', 'translate · uniform scale', 'card centre · 1', 'half centre · half ÷ card width', 460, 0, OUT, 'Snap; live thumbnail only, flat and square'),
    M('Windows', 'Snap thumbnail (fly)', 'opacity', '1', '0', 220, 380, OUT, 'Snap'),
    M('Windows', 'Real window', 'SetWindowPos (no animation)', 'current rect', 'half of work area', 0, 360, '—', 'Once, under the overlay'),
    M('Windows', 'Position marker', 'translateX', 'i × 14', '(i±1) × 14', 420, 0, OUT, 'Each detent'),
    M('Windows', 'Label', 'opacity', '0', '1', 160, 0, OUT, 'Detent lands'),
    // Toast
    M('Toast', 'Pill', 'translateY · opacity', '+8 · 0', '0 · 1', 260, 0, OUT, 'Shown only after overlays close'),
    M('Toast', 'Pill', 'scale', '0.96', '1', 420, 0, SPR, 'Show'),
    M('Toast', 'Pill (exit)', 'opacity', '1', '0', 200, 1800, IN, 'Hold 1.8 s'),
    // Knob LCD — 60 fps, translate + opacity only
    M('Knob LCD', 'Content layer (screen change)', 'translateX', '±20', '0', 380, 0, OUT, 'Mode change: + going deeper, − going back; cover and footer stay'),
    M('Knob LCD', 'Content layer (screen change)', 'opacity', '0', '1', 220, 0, OUT, 'Mode change'),
    M('Knob LCD', 'Track layer (reveal out)', 'translateY · opacity', '0 · 1', '−8 · 0', 190, 0, IN, 'First volume detent (opacity 150 ms)'),
    M('Knob LCD', 'Volume layer (reveal in)', 'translateY', '+6', '0', 340, 50, SPR, 'First volume detent'),
    M('Knob LCD', 'Volume layer (reveal in)', 'opacity', '0', '1', 180, 50, OUT, 'First volume detent'),
    M('Knob LCD', 'Volume layer (hide)', 'translateY · opacity', '0 · 1', '+6 · 0', 190, 0, IN, '1.4 s after the last detent and Sonos confirmed (opacity 170 ms)'),
    M('Knob LCD', 'Track layer (return)', 'translateY · opacity', '−8 · 0', '0 · 1', 420, 90, OUT, 'After hide (opacity 320 ms)'),
    M('Knob LCD', 'Cover', 'swap', 'previous', 'new', 0, 0, '—', 'Instant, never crossfaded'),
    M('Knob LCD', 'Cover (show/hide)', 'opacity', '0 / 0.8', '0.8 / 0', 240, 0, OUT, 'Entering / leaving Windows or the idle view'),
    M('Knob LCD', 'Footer icon ink', 'crossfade', 'old tone', 'new tone', 160, 0, OUT, 'Button state changes'),
    M('Knob LCD', 'Meta / status line', 'opacity', '0', '1', 160, 0, OUT, 'Text swaps at rest, then fades in'),
    M('Knob LCD', 'Seek digits', '—', '—', '—', 0, 0, '—', 'Redraw when a detent lands; no counting')
  ];
  const blur = [
    { surf: 'Music explorer', source: 'Desktop snapshot at open', radius: '36 px', saturate: '1.3', tint: 'rgba(8,8,10,0.50)', ambient: 'Focused cover, pre-blurred 90 px, saturate 1.5, opacity 0.50, 160 px bleed; crossfade A↔B 600 ms', sheen: 'None' },
    { surf: 'Up next', source: 'Desktop snapshot at open', radius: '36 px', saturate: '1.3', tint: 'rgba(8,8,10,0.55)', ambient: 'Focused track cover, pre-blurred 90 px, saturate 1.5, opacity 0.45, 160 px bleed; crossfade A↔B 600 ms', sheen: 'None' },
    { surf: 'Window picker · Frosted (default)', source: 'Desktop snapshot at open', radius: '40 px', saturate: '1.6', tint: 'rgba(10,10,12,0.50)', ambient: 'None', sheen: 'None (the 6 % sheen is dropped)' },
    { surf: 'Window picker · No background', source: '—', radius: '—', saturate: '—', tint: 'rgba(0,0,0,0.55) flat', ambient: 'None', sheen: 'None; labels get the text shadow 0 1px 2px / 0.6' },
    { surf: 'Toast', source: 'Desktop snapshot at show', radius: '24 px', saturate: '1', tint: 'rgba(24,24,26,0.62) + 1 px rgba(255,255,255,0.2)', ambient: 'None', sheen: 'None' },
    { surf: 'Small-art mat', source: 'The cover itself', radius: '24 px (pre-rendered)', saturate: '1', tint: 'rgba(0,0,0,0.35)', ambient: '—', sheen: 'Sharp cover centred at ≤ 1.5× native, 1 px inset rgba(255,255,255,0.12)' }
  ];
  const C = (surf, ctx, text, lim) => ({ surf, ctx, text, lim });
  const copy = [
    C('Knob heading', 'Recently Added list', 'RECENTLY ADDED', 138),
    C('Knob heading', 'Explorer mirror · Recently Added', 'RECENT', 138),
    C('Knob heading', 'Explorer mirror · Favourite playlists', 'FAVOURITES', 138),
    C('Knob heading', 'Up next mirror', 'UP NEXT', 138),
    C('Knob heading', 'Tracks', 'TRACKS', 138),
    C('Knob heading', 'Seek', 'SEEK', 138),
    C('Knob meta', 'List position', '12 / 96', 170),
    C('Knob meta', 'End of Recently Added', '96 / 96 · end', 170),
    C('Knob meta', 'Play next · progress', 'Queueing… 3 of 9', 170),
    C('Knob meta', 'Play next · success (1.5 s)', 'Queued next', 170),
    C('Knob meta', 'Play next · failed', 'Nothing added · retry', 170),
    C('Knob meta', 'Play next · partial', 'Partly queued', 170),
    C('Knob meta', 'Play next · song changed', 'Song changed · retry', 170),
    C('Knob meta', 'Play next · AirPlay', 'AirPlay · use Play', 170),
    C('Knob meta', 'Play next · radio', 'Radio · use Play', 170),
    C('Knob meta', 'Play next · line-in / TV', 'Line-in · use Play', 170),
    C('Knob meta', 'Play next · nothing playing', 'Nothing playing · Play', 170),
    C('Knob meta', 'Play next · Sonos shuffle on', 'Shuffle on · turn it off', 170),
    C('Knob meta', 'Explorer loading', 'Loading…', 170),
    C('Knob meta', 'Favourites empty', 'No favourites yet', 170),
    C('Knob meta', 'Tracks', 'Press 4 to skip', 170),
    C('Knob meta', 'Tracks · shuffle', '4 / 12 · shuffle', 170),
    C('Knob meta', 'Up next · AirPlay', 'Up next is in Music app', 170),
    C('Knob meta', 'Up next · radio', 'Radio · no Up next', 170),
    C('Knob meta', 'Seek · radio', 'Can’t seek · radio', 170),
    C('Knob meta', 'Seek · AirPlay', 'Can’t seek · AirPlay', 170),
    C('Knob meta', 'Up next position', '5 / 12 · playing', 170),
    C('Knob meta', 'Up next · loading', 'Loading queue…', 170),
    C('Knob meta', 'Like · on', 'Liked', 170),
    C('Knob meta', 'Like · already liked (add-only, r2.2)', 'Unfavourite in Music app', 170),
    C('Knob meta', 'Like · save failed', 'Didn’t save · try again', 170),
    C('Knob meta', 'Seek · unknown or over-long length', 'Can’t seek · no length', 170),
    C('Knob meta', 'Explorer · Sonos down (Play dimmed)', 'Sonos unavailable', 170),
    C('Knob meta', 'Unplayable list item', 'Not available', 170),
    C('Knob meta', 'Shuffle off refused · queue changed', 'Queue changed', 170),
    C('Knob meta', 'Shuffle failed', 'Didn’t shuffle · try again', 170),
    C('Knob meta', 'Shuffle · < 2 upcoming', 'Nothing to shuffle', 170),
    C('Knob meta', 'Busy · start running', 'Starting…', 170),
    C('Knob meta', 'Busy · pause running', 'Pausing…', 170),
    C('Knob meta', 'Busy · shuffle running', 'Shuffling…', 170),
    C('Knob meta', 'Play next · song lookup (before k counts)', 'Finding songs…', 170),
    C('Knob meta', 'Apple Music library failed', 'Library not loaded', 170),
    C('Knob meta', 'Sonos group changed during an action', 'Speaker group changed', 170),
    C('Knob meta', 'PC refused to open an overlay', 'Couldn’t open on screen', 170),
    C('Knob line 14 px', 'Retry hint under Library not loaded', 'Home, then Browse', 170),
    C('Knob meta', 'Like · state unknown', 'Checking likes…', 170),
    C('Knob meta', 'Like · non-catalog row', 'Not an Apple Music song', 170),
    C('Knob meta', 'Like · sign-in expired', 'Sign-in expired', 170),
    C('Knob meta', 'Shuffle · companion', 'Shuffle on', 170),
    C('Knob meta', 'Shuffle · off', 'Shuffle off · in order', 170),
    C('Knob meta', 'Shuffle · Sonos (> 60 left)', 'Sonos is shuffling', 170),
    C('Knob meta', 'Windows · one side', 'Left: Claude · pick right', 170),
    C('Knob meta', 'Snap · hung', 'Slack not responding', 170),
    C('Knob meta', 'Snap · move failed', 'Couldn’t move Slack', 170),
    C('Knob meta', 'Snap · too big', 'Slack can’t fit half', 170),
    C('Knob line 14 px', 'Tracks · now (long titles end in …)', 'Now: Tick of the Clock', 170),
    C('Knob line 14 px', 'Tracks · Sonos shuffle, next unknown', 'Next: shuffle pick', 170),
    C('Knob line 14 px', 'Tracks · shuffle, previous', 'Prev: last played', 170),
    C('Knob line 14 px', 'Tracks · repeat all, last track', 'Next: back to track 1', 170),
    C('Knob line 14 px', 'Seek · length', 'of 4:47', 170),
    C('Knob line 14 px', 'Seek · waiting for Sonos', 'Jumping…', 170),
    C('Knob line 14 px', 'Seek · failed', 'Didn’t jump · try again', 170),
    C('Knob line 14 px', 'Seek · limit', 'Stops 3 s before end', 170),
    C('Knob status 12 px', 'Home · starting', 'Starting…', 160),
    C('Knob status 12 px', 'Home · playlist partly playable (3 s)', 'Playing 33 of 34', 160),
    C('Knob status 12 px', 'Home · start failed', 'Didn’t start', 160),
    C('Knob status 12 px', 'Home · album blocked', 'Album unavailable', 160),
    C('Knob status 12 px', 'Home', 'Paused', 160),
    C('Knob status 12 px', 'Home · Sonos down', 'Sonos unavailable', 160),
    C('Knob status 12 px', 'Home · group changed', 'Speaker group changed', 160),
    C('Knob title 22 px', 'PC not connected', 'Waiting for PC', 170),
    C('Toast', 'Play next · success', 'Queued next · Moon Safari', 0),
    C('Toast', 'Play next · AirPlay / radio / line-in', 'Not playing from the queue · use Play', 0),
    C('Toast', 'Play next · nothing playing', 'Nothing playing · use Play', 0),
    C('Toast', 'Play next · Sonos shuffle', 'Shuffle is on · turn it off to play next', 0),
    C('Toast', 'Play next · failed', 'Couldn’t queue Moon Safari · nothing added', 0),
    C('Toast', 'Play next · partial', 'Partly queued · check the Sonos queue', 0),
    C('Toast', 'Play next · song changed', 'Song changed · try again', 0),
    C('Toast', 'Start · success (after overlay closes)', 'Playing PAPER LANTERN Ep. 1', 0),
    C('Toast', 'Start · partly playable', 'Playing 33 of 34 · 1 song unavailable', 0),
    C('Toast', 'Start · partly playable (plural)', 'Playing 31 of 34 · 3 songs unavailable', 0),
    C('Toast', 'Start · album blocked', 'Kind of Blue can’t play · a song is unavailable', 0),
    C('Toast', 'Start · failed', 'Couldn’t start PAPER LANTERN Ep. 1', 0),
    C('Toast', 'Switch', 'Claude · Nano D Control Center', 0),
    C('Toast', 'Snap · both sides', 'Side by side · Claude and Slack', 0),
    C('Toast', 'Snap · one side, closed', 'Claude left · Chrome right', 0),
    C('Toast', 'Like · sign-in expired (after close)', 'Apple Music sign-in expired · open Settings', 0),
    C('Overlay', 'Favourites empty · title', 'No favourite playlists yet', 0),
    C('Overlay', 'Favourites empty · help', 'Star a playlist in the Music app. It appears here within a few minutes.', 0),
    C('Overlay', 'Recently Added empty · title', 'Nothing recently added', 0),
    C('Overlay', 'Recently Added empty · help', 'Add an album or a playlist to your library in the Music app.', 0),
    C('Overlay', 'Library error · title', 'Library not loaded', 0),
    C('Overlay', 'Library error · help', 'Go Home, then Browse to retry.', 0),
    C('Overlay', 'Sign-in expired, nothing cached · title', 'Apple Music sign-in expired', 0),
    C('Overlay', 'Sign-in expired, nothing cached · help', 'Open Settings on your PC to sign in again.', 0),
    C('Knob idle row', 'Slot 1 label (follows the icon, 46 px column)', 'Play', 46),
    C('Knob idle row', 'Slot 1 label while playing', 'Pause', 46),
    C('Overlay', 'Up next · queue from another app', 'Sonos queue', 0),
    C('Overlay', 'Up next · Sonos shuffle card', 'Sonos is shuffling the rest · order isn’t shown', 0),
    C('Overlay', 'Snap slot · one side preview', 'Right · keeps Chrome', 0)
  ];
  window.NANO_R2 = { motion, blur, copy, curves: { OUT, IN, SPR, LIN } };
})();
